/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project.deliverable;

import connection.database.ConnectDatabase;
import javax.swing.JOptionPane;

/**
 *
 * @author Muhammad Junaid Tari
 */
public class AddQuestionReviewer extends javax.swing.JFrame {

    ConnectDatabase cb=new ConnectDatabase();
    public AddQuestionReviewer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        questrev_id = new javax.swing.JTextField();
        questrev_name = new javax.swing.JTextField();
        questrev_cntctno = new javax.swing.JTextField();
        questrev_address = new javax.swing.JTextField();
        questrev_email = new javax.swing.JTextField();
        questrev_type = new javax.swing.JTextField();
        questrev_password = new javax.swing.JTextField();
        questrev_save = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        exit_um = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setLocation(new java.awt.Point(350, 50));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jLabel2.setText("Enter Id Of Question Setter");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 431, -1));

        jLabel3.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jLabel3.setText("Enter name of Question Setter");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 423, -1));

        jLabel4.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jLabel4.setText("Enter contact number ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 240, -1));

        jLabel5.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jLabel5.setText("Enter Address ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 159, -1));

        jLabel6.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jLabel6.setText("Enter Email");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 159, -1));

        jLabel9.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jLabel9.setText("Enter Type");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 159, -1));

        jLabel7.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jLabel7.setText("Enter Password");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 180, -1));
        getContentPane().add(questrev_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 70, 250, 40));
        getContentPane().add(questrev_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, 250, 40));
        getContentPane().add(questrev_cntctno, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 170, 250, 40));
        getContentPane().add(questrev_address, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 220, 250, 40));
        getContentPane().add(questrev_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 270, 250, 40));
        getContentPane().add(questrev_type, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 320, 250, 40));
        getContentPane().add(questrev_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 370, 250, 40));

        questrev_save.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        questrev_save.setText("Save record");
        questrev_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                questrev_saveActionPerformed(evt);
            }
        });
        getContentPane().add(questrev_save, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 430, -1, -1));

        cancel.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        getContentPane().add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 430, 86, -1));

        jLabel1.setFont(new java.awt.Font("Algerian", 0, 24)); // NOI18N
        jLabel1.setText("                  Add Question Reviewer Information");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 580, 25));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exit_um.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        exit_um.setText("Logout");
        exit_um.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit_umActionPerformed(evt);
            }
        });
        jPanel1.add(exit_um, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 430, 140, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/deliverable/banner-bg-home.png"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -80, 720, 570));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void questrev_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_questrev_saveActionPerformed

        try
        {
            String query="insert into Member(memId,memName,cntctNO,Address,Email,Type,Password)"+" values('"+this.questrev_id.getText()+"','"+this.questrev_name.getText()+"','"+this.questrev_cntctno.getText()+"','"+this.questrev_address.getText()+"','"+this.questrev_email.getText()+"','"+this.questrev_type.getText()+"','"+this.questrev_password.getText()+"')";
            cb.insertData(query);
            JOptionPane.showMessageDialog(null,"Data Saved");
            this.questrev_id.setText(null);
            this.questrev_name.setText(null);
            this.questrev_address.setText(null);
            this.questrev_cntctno.setText(null);
            this.questrev_email.setText(null);
            this.questrev_type.setText(null);
            this.questrev_type.setText(null);
            this.questrev_password.setText(null);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
    }//GEN-LAST:event_questrev_saveActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        this.setVisible(false);
    UserMaintainer um= new UserMaintainer();
    um.setVisible(true);
    }//GEN-LAST:event_cancelActionPerformed

    private void exit_umActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit_umActionPerformed
        this.setVisible(false);
        StartProject sp=new StartProject();
        sp.setVisible(true);
    }//GEN-LAST:event_exit_umActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddQuestionReviewer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddQuestionReviewer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddQuestionReviewer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddQuestionReviewer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddQuestionReviewer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel;
    private javax.swing.JButton exit_um;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField questrev_address;
    private javax.swing.JTextField questrev_cntctno;
    private javax.swing.JTextField questrev_email;
    private javax.swing.JTextField questrev_id;
    private javax.swing.JTextField questrev_name;
    private javax.swing.JTextField questrev_password;
    private javax.swing.JButton questrev_save;
    private javax.swing.JTextField questrev_type;
    // End of variables declaration//GEN-END:variables
}
