/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project.deliverable;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Muhammad Junaid Tari
 */

public class Candidate_Test extends javax.swing.JFrame {

    Connection conn;
    ResultSet rset;
    Statement stmt;
    int rollno;
    String deg;
    int fid;
    int []n=new int[5];
    int l=0;
    int k=0;
    int m=0;
    int counter=0;
    int arrsize=0;
    String canans;
    String []strar1=new String[10];
    String []strar2=new String[10];
    String []strar3=new String[10];
    String []strar4=new String[10];
    String []strar5=new String[10];
    String []strar6=new String[10];
    
    public Candidate_Test() {
        
        initComponents();
        rollno=Candidate_Login.rno;
        try
        {
            conn=DriverManager.getConnection("jdbc:ucanaccess://E:\\5th semester\\java\\java.accdb");   
            stmt=conn.createStatement();
            rset=stmt.executeQuery("Select Degree from Candidate where ROLLNO='"+rollno+"'");
            while(rset.next())
            {
               deg= rset.getString("Degree");
               //System.out.println("out:"+deg);

            }
            rset=stmt.executeQuery("Select FormatId from TestFormat where Degree='"+deg+"'");
            while(rset.next())
            {
                fid=rset.getInt("FormatId");
                // System.out.println("out:"+fid);
            }
            rset=stmt.executeQuery("Select CategoryId from FormatCategory where Format_id='"+fid+"'");
            while(rset.next())
            {
                n[l]=rset.getInt("CategoryId");
                //System.out.println("rset:"+n[l]);
                l++;
            }
            arrsize=l;
            
            
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        questionarea = new javax.swing.JTextArea();
        opt_1 = new javax.swing.JRadioButton();
        opt_2 = new javax.swing.JRadioButton();
        opt_3 = new javax.swing.JRadioButton();
        opt_4 = new javax.swing.JRadioButton();
        Timer = new javax.swing.JLabel();
        nextquest = new javax.swing.JButton();
        skipquest = new javax.swing.JButton();
        savequest = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        starttest = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        questionarea.setColumns(20);
        questionarea.setRows(5);
        jScrollPane1.setViewportView(questionarea);

        opt_1.setText("Option 1");
        opt_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt_1ActionPerformed(evt);
            }
        });

        opt_2.setText("Option 2");
        opt_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt_2ActionPerformed(evt);
            }
        });

        opt_3.setText("Option 3");
        opt_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt_3ActionPerformed(evt);
            }
        });

        opt_4.setText("Option 4");
        opt_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt_4ActionPerformed(evt);
            }
        });

        Timer.setText("Timer");

        nextquest.setText("Next>>");

        skipquest.setText("Skip");

        savequest.setText("Submit");
        savequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savequestActionPerformed(evt);
            }
        });

        jButton4.setText("Show 5 Questions ");

        jButton5.setText("Show 10 Questions");

        starttest.setText("Start Test");
        starttest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                starttestActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(opt_1)
                            .addGap(45, 45, 45)
                            .addComponent(opt_2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(opt_3)
                            .addGap(54, 54, 54)
                            .addComponent(opt_4))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(skipquest, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(137, 137, 137)
                            .addComponent(savequest, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(starttest))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Timer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(24, 24, 24))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(nextquest, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(starttest)
                    .addComponent(Timer, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addGap(40, 40, 40)
                        .addComponent(jButton5))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(opt_1)
                    .addComponent(opt_2)
                    .addComponent(opt_3)
                    .addComponent(opt_4))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(skipquest)
                    .addComponent(nextquest)
                    .addComponent(savequest))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void starttestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_starttestActionPerformed

        try 
        {
            stmt.executeUpdate("insert into Test(canROLLNO,format_Id)"+"values('"+rollno+"','"+fid+"')");
            if(k<=arrsize)
            {
               rset=stmt.executeQuery("select QuestionDesc,1stOption,2ndOption,3rdOption,4thOption,crtOption from Question where cat_id='"+n[k]+"'");
               while(rset.next())
               {
                   strar1[m]=rset.getString("QuestionDesc");
                   strar2[m]=rset.getString("1stOption");
                   strar3[m]=rset.getString("2ndOption");
                   strar4[m]=rset.getString("3rdOption");
                   strar5[m]=rset.getString("4thOption");
                   strar6[m]=rset.getString("crtOption");
                   System.out.println("dis:"+strar6[m]);
                   m++;
               }
               m=0;
               this.questionarea.setText(strar1[m]);
               this.opt_1.setText(strar2[m]);
               this.opt_2.setText(strar3[m]);
               this.opt_3.setText(strar4[m]);
               this.opt_4.setText(strar5[m]);
               counter++;
               k++;
               
               
            }
        }
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
        //stmt.executeQuery("select QuestionDesc,1stOption,2ndOption,3rdOption,4thOption,crtOption from Question where ");
    }//GEN-LAST:event_starttestActionPerformed

    private void savequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savequestActionPerformed

        this.opt_1.setSelected(false);
        this.opt_2.setSelected(false);
        this.opt_3.setSelected(false);
        this.opt_4.setSelected(false);
        try
        {
            System.out.println("m:"+m);
            System.out.println("canans:"+canans);
            System.out.println("strar[m]:"+strar6[m]);
            stmt.executeUpdate("insert into CompletedTest(canROLLNo,canAns,crtAns)"+"values('"+rollno+"','"+canans+"','"+strar6[m]+"')");
            if(counter<10&&m<=9)
            {
            m++;
            System.out.println("m:"+m);
            this.questionarea.setText(strar1[m]);
            this.opt_1.setText(strar2[m]);
            this.opt_2.setText(strar3[m]);
            this.opt_3.setText(strar4[m]);
            this.opt_4.setText(strar5[m]);
            }
            else
            {
                counter=0;
                //stmt.executeUpdate("insert into Test(canROLLNO,format_Id)"+"values('"+rollno+"','"+fid+"')";
                if(k<arrsize)
                {
                    rset=stmt.executeQuery("select QuestionDesc,1stOption,2ndOption,3rdOption,4thOption,crtOption from Question where cat_id='"+n[k]+"'");
                    k++;
                    m=0;
                    while(rset.next())
                    {
                        strar1[m]=rset.getString("QuestionDesc");
                   strar2[m]=rset.getString("1stOption");
                   strar3[m]=rset.getString("2ndOption");
                   strar4[m]=rset.getString("3rdOption");
                   strar5[m]=rset.getString("4thOption");
                   strar6[m]=rset.getString("crtOption");
                   m++;

                    }
                    m=0;
                    this.questionarea.setText(strar1[m]);
                    this.opt_1.setText(strar2[m]);
                   this.opt_2.setText(strar3[m]);
                   this.opt_3.setText(strar4[m]);
                     this.opt_4.setText(strar5[m]);
                   if(k==arrsize)
                   {
                    stmt.executeUpdate("insert into CompletedTest(canROLLNo,canAns,crtAns)"+"values('"+rollno+",'"+canans+"','"+strar6[m]+"')");
                
                   }
                }
                
                  else
                  {
                
                    JOptionPane.showMessageDialog(null, "Test Question Have End");
                   }
                }
                counter++;
            }
        catch (SQLException ex)
                {
                  JOptionPane.showMessageDialog(null, ex.getMessage());
                }

    }//GEN-LAST:event_savequestActionPerformed

    private void opt_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt_1ActionPerformed

        canans=this.opt_1.getText();
              
    }//GEN-LAST:event_opt_1ActionPerformed

    private void opt_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt_2ActionPerformed
       canans=this.opt_2.getText();
       System.out.println("canans:"+canans);
      
       
    }//GEN-LAST:event_opt_2ActionPerformed

    private void opt_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt_3ActionPerformed
       canans=this.opt_3.getText();
       System.out.println("canans");

    }//GEN-LAST:event_opt_3ActionPerformed

    private void opt_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt_4ActionPerformed
       canans=this.opt_4.getText();
       System.out.println("canans:"+canans);
 
    }//GEN-LAST:event_opt_4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Candidate_Test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Candidate_Test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Candidate_Test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Candidate_Test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Candidate_Test().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Timer;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton nextquest;
    private javax.swing.JRadioButton opt_1;
    private javax.swing.JRadioButton opt_2;
    private javax.swing.JRadioButton opt_3;
    private javax.swing.JRadioButton opt_4;
    private javax.swing.JTextArea questionarea;
    private javax.swing.JButton savequest;
    private javax.swing.JButton skipquest;
    private javax.swing.JButton starttest;
    // End of variables declaration//GEN-END:variables
}
