/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project.deliverable;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.StringTokenizer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Muhammad Junaid Tari
 */
public class QuestionReviewer extends javax.swing.JFrame {

    String str="";
    String []str1=new String[10];
    String []str2=new String[10];
    String []str3=new String[10];
    String []str4=new String[10];
    String []str5=new String[10];
    String []str6=new String[10];
    String sr1,sr2,sr3,sr4,sr5,sr6;
    Connection conn=null;
    Statement stmt=null;
    ResultSet rset=null;
    
    int k=0;
    int l=0;
    int n=0;
    static int questid;
    public QuestionReviewer() {
        initComponents();
        this.edit_ok.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        questarea = new javax.swing.JTextArea();
        changeopt = new javax.swing.JButton();
        deletequest = new javax.swing.JButton();
        category = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        next = new javax.swing.JButton();
        editmsg = new javax.swing.JLabel();
        edit_ok = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        questarea.setColumns(20);
        questarea.setRows(5);
        jScrollPane1.setViewportView(questarea);

        changeopt.setText("Edit Option");
        changeopt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeoptActionPerformed(evt);
            }
        });

        deletequest.setText("Delete Question");
        deletequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletequestActionPerformed(evt);
            }
        });

        category.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Category", "Physics", "Chemistry", "English", "Math", " " }));
        category.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryActionPerformed(evt);
            }
        });

        jLabel1.setText("Select Category");

        jButton4.setText("Enter Question");

        next.setText("Next>>>>");
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });

        edit_ok.setText("Ok");
        edit_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_okActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(category, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(deletequest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(changeopt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(next, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(editmsg, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addComponent(edit_ok, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(category, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(editmsg)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(changeopt)
                        .addGap(18, 18, 18)
                        .addComponent(deletequest)
                        .addGap(27, 27, 27)
                        .addComponent(jButton4)
                        .addGap(29, 29, 29)
                        .addComponent(next))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edit_ok)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void categoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryActionPerformed

     
        try {
            conn=DriverManager.getConnection("jdbc:ucanaccess://E:\\5th semester\\java\\java.accdb");
            stmt=conn.createStatement();
            if(category.getSelectedItem().toString().equals("Physics"))
            {
                rset=stmt.executeQuery("Select QuestionDesc,1stOption,2ndOption,3rdOption,4thOption,crtOption,cat_id from Question where cat_id=1");
                while(rset.next())
                {
                    str1[k]=rset.getString("QuestionDesc");
                    str2[k]=rset.getString("1stOption");
                    str3[k]=rset.getString("2ndOption");
                    str4[k]=rset.getString("3rdOption");
                    str5[k]=rset.getString("4thOption");
                    str6[k]=rset.getString("crtOption");
                    k++;
                }
                n=0;
                this.questarea.setText(str1[l]+"\n");
                this.questarea.append(str2[l]+"\n");
                this.questarea.append(str3[l]+"\n");
                this.questarea.append(str4[l]+"\n");
                this.questarea.append(str5[l]+"\n");
                this.questarea.append(str6[l]+"\n");
                this.questarea.setEditable(false);
            }
        } catch (SQLException ex) {
            Logger.getLogger(QuestionReviewer.class.getName()).log(Level.SEVERE, null, ex);
        }
         
        
    }//GEN-LAST:event_categoryActionPerformed

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed

        l++;
        n=l;
        try
        {
          this.questarea.setText(str1[l]+"\n");
          this.questarea.append(str2[l]+"\n");
          this.questarea.append(str3[l]+"\n");
          this.questarea.append(str4[l]+"\n");
          this.questarea.append(str5[l]+"\n");
          this.questarea.append(str6[l]+"\n");
          this.questarea.setEditable(false);
        }
        catch(Exception err)
        {
            JOptionPane.showMessageDialog(null, "No more Questions for this category!");
        }
        
    }//GEN-LAST:event_nextActionPerformed

    private void changeoptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeoptActionPerformed

        
        this.editmsg.setText("Please edit question now");
        this.edit_ok.setVisible(true);
        this.questarea.setEditable(true);
        
    }//GEN-LAST:event_changeoptActionPerformed

    private void edit_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_okActionPerformed

        str=this.questarea.getText();
        StringTokenizer token=new StringTokenizer(str,"\n");
        str1[0]=token.nextToken();
        str2[0]=token.nextToken();
        str3[0]=token.nextToken();
        str4[0]=token.nextToken();
        str5[0]=token.nextToken();
        str6[0]=token.nextToken();
        try {
            stmt.executeUpdate("update Question set 1stOption='"+str2[0]+"',2ndOption='"+str3[0]+"',3rdOption='"+str4[0]+"',4thOption='"+str5[0]+"',crtOption='"+str6[0]+"'where QuestionDesc='"+str1[0]+"'");
            JOptionPane.showMessageDialog(null, "Options updated successfully");
            this.edit_ok.setVisible(false);
            this.editmsg.setText(null);
        } catch (SQLException ex) {
            Logger.getLogger(QuestionReviewer.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_edit_okActionPerformed

    private void deletequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletequestActionPerformed

        this.questarea.setText("");
        this.questarea.setEditable(true);
        JOptionPane.showMessageDialog(null, "Question no "+(n+1)+" has deleted.");
        try
        {
            rset=stmt.executeQuery("select questionId from Question where QuestionDesc='"+str1[n]+"'");
            while(rset.next())
            {
                questid=rset.getInt("questionId");
            }
            JOptionPane.showMessageDialog(null, "Question id="+questid);
        } 
        catch (SQLException ex)
        {
            Logger.getLogger(QuestionReviewer.class.getName()).log(Level.SEVERE, null, ex);
        }
        EnterQuestion quest=new EnterQuestion(this);
        quest.setVisible(true);
        quest.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_deletequestActionPerformed

    public void display()
    {
        try 
        {
            rset=stmt.executeQuery("Select questionId,QuestionDesc,1stOption,2ndOption,3rdOption,4thOption,crtOption from Question where questionId='"+questid+"'");
            while(rset.next())
            {
                sr1=rset.getString("QuestionDesc");
                sr2=rset.getString("1stOption");
                sr3=rset.getString("2ndOption");
                sr4=rset.getString("3rdOption");
                sr5=rset.getString("4thOption");
                sr6=rset.getString("crtOption");

            }
            
            
            
        }
        catch (SQLException ex) {
            Logger.getLogger(QuestionReviewer.class.getName()).log(Level.SEVERE, null, ex.getMessage());
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuestionReviewer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuestionReviewer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuestionReviewer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuestionReviewer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuestionReviewer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox category;
    private javax.swing.JButton changeopt;
    private javax.swing.JButton deletequest;
    private javax.swing.JButton edit_ok;
    private javax.swing.JLabel editmsg;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton next;
    public javax.swing.JTextArea questarea;
    // End of variables declaration//GEN-END:variables
}

