/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project.deliverable;

import connection.database.ConnectDatabase;
import java.awt.HeadlessException;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;

/**
 *
 * @author Muhammad Junaid Tari
 */
public class TenQuestions extends javax.swing.JFrame {

    ResultSet rset;
     int rollno;
    String deg;
    String canans;
    int fid;
    int l=0;
    int m=0;
    int k=0;
    int arr=0;
    int time;
    int arrsize;
    int counter;
    int j=0;
    int []n=new int[10];
    String []strar1=new String[10];
    String []strar2=new String[10];
    String []strar3=new String[10];
    String []strar4=new String[10];
    String []strar5=new String[10];
    String []strar6=new String[10];
    String str1;
    String str2;
    String str3;
    String str4;
    String str5;
    int questid;
    int testid;
    String query;
    ConnectDatabase cb=new ConnectDatabase();
    boolean is_completed=false;
    public TenQuestions() {
        initComponents();
         rollno=Candidate_Login.rno;
        this.submit1.setEnabled(false);
        this.submit2.setEnabled(false);
        this.submit3.setEnabled(false);
        this.submit4.setEnabled(false);
        this.submit5.setEnabled(false);
        this.submit6.setEnabled(false);
        this.submit7.setEnabled(false);
        this.submit8.setEnabled(false);
        this.submit9.setEnabled(false);
        this.submit10.setEnabled(false);
        this.skip1.setEnabled(false);
        this.skip2.setEnabled(false);
        this.skip3.setEnabled(false);
        this.skip4.setEnabled(false);
        this.skip5.setEnabled(false);
        this.skip6.setEnabled(false);
        this.skip7.setEnabled(false);
        this.skip8.setEnabled(false);
        this.skip9.setEnabled(false);
        this.skip10.setEnabled(false);
        try
        {
            
            query="Select Degree from Candidate where ROLLNO='"+rollno+"'";
            rset=cb.getData(query);
            while(rset.next())
            {
               deg= rset.getString("Degree");
               //System.out.println("out:"+deg);

            }
            query="Select FormatId from TestFormat where Degree='"+deg+"'";
            rset=cb.getData(query);
            while(rset.next())
            {
                fid=rset.getInt("FormatId");
                // System.out.println("out:"+fid);
            }
            query="Select CategoryId from FormatCategory where Format_id='"+fid+"'";
            rset=cb.getData(query);
            while(rset.next())
            {
                n[l]=rset.getInt("CategoryId");
                //System.out.println("rset:"+n[l]);
                l++;
            }
            arrsize=l;
            
            
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        starttest = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        timerlbl = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        questarea1 = new javax.swing.JTextArea();
        opt_1 = new javax.swing.JRadioButton();
        opt_2 = new javax.swing.JRadioButton();
        opt_3 = new javax.swing.JRadioButton();
        opt_4 = new javax.swing.JRadioButton();
        submit1 = new javax.swing.JButton();
        skip1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        questarea2 = new javax.swing.JTextArea();
        opt2_1 = new javax.swing.JRadioButton();
        opt2_2 = new javax.swing.JRadioButton();
        opt2_3 = new javax.swing.JRadioButton();
        opt2_4 = new javax.swing.JRadioButton();
        submit2 = new javax.swing.JButton();
        skip2 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        questarea3 = new javax.swing.JTextArea();
        submit3 = new javax.swing.JButton();
        skip3 = new javax.swing.JButton();
        opt3_1 = new javax.swing.JRadioButton();
        opt3_2 = new javax.swing.JRadioButton();
        opt3_3 = new javax.swing.JRadioButton();
        opt3_4 = new javax.swing.JRadioButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        questarea4 = new javax.swing.JTextArea();
        opt4_1 = new javax.swing.JRadioButton();
        opt4_2 = new javax.swing.JRadioButton();
        opt4_3 = new javax.swing.JRadioButton();
        opt4_4 = new javax.swing.JRadioButton();
        submit4 = new javax.swing.JButton();
        skip4 = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        questarea5 = new javax.swing.JTextArea();
        opt5_1 = new javax.swing.JRadioButton();
        opt5_2 = new javax.swing.JRadioButton();
        opt5_3 = new javax.swing.JRadioButton();
        opt5_4 = new javax.swing.JRadioButton();
        submit5 = new javax.swing.JButton();
        skip5 = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        questarea6 = new javax.swing.JTextArea();
        opt6_1 = new javax.swing.JRadioButton();
        opt6_2 = new javax.swing.JRadioButton();
        opt6_3 = new javax.swing.JRadioButton();
        opt6_4 = new javax.swing.JRadioButton();
        submit6 = new javax.swing.JButton();
        skip6 = new javax.swing.JButton();
        jScrollPane8 = new javax.swing.JScrollPane();
        questarea7 = new javax.swing.JTextArea();
        opt7_1 = new javax.swing.JRadioButton();
        opt7_2 = new javax.swing.JRadioButton();
        opt7_3 = new javax.swing.JRadioButton();
        opt7_4 = new javax.swing.JRadioButton();
        submit7 = new javax.swing.JButton();
        skip7 = new javax.swing.JButton();
        jScrollPane9 = new javax.swing.JScrollPane();
        questarea8 = new javax.swing.JTextArea();
        submit8 = new javax.swing.JButton();
        skip8 = new javax.swing.JButton();
        opt8_4 = new javax.swing.JRadioButton();
        opt8_3 = new javax.swing.JRadioButton();
        opt8_2 = new javax.swing.JRadioButton();
        opt8_1 = new javax.swing.JRadioButton();
        jScrollPane10 = new javax.swing.JScrollPane();
        questarea9 = new javax.swing.JTextArea();
        opt9_1 = new javax.swing.JRadioButton();
        opt9_2 = new javax.swing.JRadioButton();
        opt9_3 = new javax.swing.JRadioButton();
        opt9_4 = new javax.swing.JRadioButton();
        submit9 = new javax.swing.JButton();
        skip9 = new javax.swing.JButton();
        jScrollPane11 = new javax.swing.JScrollPane();
        questarea10 = new javax.swing.JTextArea();
        opt10_1 = new javax.swing.JRadioButton();
        opt10_2 = new javax.swing.JRadioButton();
        opt10_3 = new javax.swing.JRadioButton();
        next = new javax.swing.JButton();
        opt10_4 = new javax.swing.JRadioButton();
        submit10 = new javax.swing.JButton();
        skip10 = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(350, 0));
        setSize(new java.awt.Dimension(350, 0));

        jPanel1.setBackground(new java.awt.Color(0, 51, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        starttest.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        starttest.setText("Start");
        starttest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                starttestActionPerformed(evt);
            }
        });
        jPanel1.add(starttest, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 15, 68, -1));

        jLabel1.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jLabel1.setText("Not Failure but low aim is a crime");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 11, 340, -1));

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel3.setText("Time Left :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(611, 11, 95, -1));

        timerlbl.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        timerlbl.setText("Timer");
        jPanel1.add(timerlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(712, 11, 98, -1));

        questarea1.setColumns(20);
        questarea1.setRows(5);
        questarea1.setOpaque(false);
        jScrollPane2.setViewportView(questarea1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 49, 663, 43));

        opt_1.setOpaque(false);
        opt_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt_1ActionPerformed(evt);
            }
        });
        jPanel1.add(opt_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 94, 285, -1));

        opt_2.setOpaque(false);
        opt_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt_2ActionPerformed(evt);
            }
        });
        jPanel1.add(opt_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 122, 285, -1));

        opt_3.setOpaque(false);
        opt_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt_3ActionPerformed(evt);
            }
        });
        jPanel1.add(opt_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 94, 318, -1));

        opt_4.setOpaque(false);
        opt_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt_4ActionPerformed(evt);
            }
        });
        jPanel1.add(opt_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 122, 335, -1));

        submit1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        submit1.setText("Submit");
        submit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit1ActionPerformed(evt);
            }
        });
        jPanel1.add(submit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(708, 49, 138, -1));

        skip1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        skip1.setText("Skip");
        skip1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                skip1ActionPerformed(evt);
            }
        });
        jPanel1.add(skip1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 80, 138, -1));

        questarea2.setColumns(20);
        questarea2.setRows(5);
        questarea2.setOpaque(false);
        jScrollPane3.setViewportView(questarea2);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 145, 663, 32));

        opt2_1.setOpaque(false);
        opt2_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt2_1ActionPerformed(evt);
            }
        });
        jPanel1.add(opt2_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 188, 291, -1));

        opt2_2.setOpaque(false);
        opt2_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt2_2ActionPerformed(evt);
            }
        });
        jPanel1.add(opt2_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 213, 291, -1));

        opt2_3.setOpaque(false);
        opt2_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt2_3ActionPerformed(evt);
            }
        });
        jPanel1.add(opt2_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(301, 188, 339, -1));

        opt2_4.setOpaque(false);
        opt2_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt2_4ActionPerformed(evt);
            }
        });
        jPanel1.add(opt2_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(301, 213, 339, -1));

        submit2.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        submit2.setText("Submit");
        submit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit2ActionPerformed(evt);
            }
        });
        jPanel1.add(submit2, new org.netbeans.lib.awtextra.AbsoluteConstraints(708, 145, 138, -1));

        skip2.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        skip2.setText("Skip");
        skip2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                skip2ActionPerformed(evt);
            }
        });
        jPanel1.add(skip2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 180, 138, -1));

        questarea3.setColumns(20);
        questarea3.setRows(5);
        questarea3.setText("\n");
        questarea3.setOpaque(false);
        jScrollPane4.setViewportView(questarea3);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 241, 663, 32));

        submit3.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        submit3.setText("Submit");
        submit3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit3ActionPerformed(evt);
            }
        });
        jPanel1.add(submit3, new org.netbeans.lib.awtextra.AbsoluteConstraints(708, 241, 138, -1));

        skip3.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        skip3.setText("Skip");
        skip3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                skip3ActionPerformed(evt);
            }
        });
        jPanel1.add(skip3, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 270, 138, -1));

        opt3_1.setOpaque(false);
        opt3_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt3_1ActionPerformed(evt);
            }
        });
        jPanel1.add(opt3_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 284, 287, -1));

        opt3_2.setOpaque(false);
        opt3_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt3_2ActionPerformed(evt);
            }
        });
        jPanel1.add(opt3_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 309, 286, -1));

        opt3_3.setOpaque(false);
        opt3_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt3_3ActionPerformed(evt);
            }
        });
        jPanel1.add(opt3_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 280, 376, -1));

        opt3_4.setOpaque(false);
        opt3_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt3_4ActionPerformed(evt);
            }
        });
        jPanel1.add(opt3_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 310, 376, -1));

        questarea4.setColumns(20);
        questarea4.setRows(5);
        questarea4.setOpaque(false);
        jScrollPane5.setViewportView(questarea4);

        jPanel1.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 332, 663, 32));

        opt4_1.setOpaque(false);
        opt4_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt4_1ActionPerformed(evt);
            }
        });
        jPanel1.add(opt4_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 371, 287, -1));

        opt4_2.setOpaque(false);
        opt4_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt4_2ActionPerformed(evt);
            }
        });
        jPanel1.add(opt4_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 392, 287, -1));

        opt4_3.setOpaque(false);
        opt4_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt4_3ActionPerformed(evt);
            }
        });
        jPanel1.add(opt4_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 371, 376, -1));

        opt4_4.setOpaque(false);
        opt4_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt4_4ActionPerformed(evt);
            }
        });
        jPanel1.add(opt4_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 392, 376, -1));

        submit4.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        submit4.setText("Submit");
        submit4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit4ActionPerformed(evt);
            }
        });
        jPanel1.add(submit4, new org.netbeans.lib.awtextra.AbsoluteConstraints(708, 332, 138, -1));

        skip4.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        skip4.setText("Skip");
        skip4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                skip4ActionPerformed(evt);
            }
        });
        jPanel1.add(skip4, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 360, 138, -1));

        questarea5.setColumns(20);
        questarea5.setRows(5);
        jScrollPane6.setViewportView(questarea5);

        jPanel1.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 415, 663, 29));

        opt5_1.setOpaque(false);
        opt5_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt5_1ActionPerformed(evt);
            }
        });
        jPanel1.add(opt5_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 290, -1));

        opt5_2.setOpaque(false);
        opt5_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt5_2ActionPerformed(evt);
            }
        });
        jPanel1.add(opt5_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 290, -1));

        opt5_3.setOpaque(false);
        opt5_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt5_3ActionPerformed(evt);
            }
        });
        jPanel1.add(opt5_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 450, 320, -1));

        opt5_4.setOpaque(false);
        opt5_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt5_4ActionPerformed(evt);
            }
        });
        jPanel1.add(opt5_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 480, 349, -1));

        submit5.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        submit5.setText("Submit");
        submit5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit5ActionPerformed(evt);
            }
        });
        jPanel1.add(submit5, new org.netbeans.lib.awtextra.AbsoluteConstraints(708, 415, 138, -1));

        skip5.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        skip5.setText("Skip");
        skip5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                skip5ActionPerformed(evt);
            }
        });
        jPanel1.add(skip5, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 450, 138, -1));

        questarea6.setColumns(20);
        questarea6.setRows(5);
        jScrollPane7.setViewportView(questarea6);

        jPanel1.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 503, 663, 28));

        opt6_1.setOpaque(false);
        opt6_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt6_1ActionPerformed(evt);
            }
        });
        jPanel1.add(opt6_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 538, 288, -1));

        opt6_2.setOpaque(false);
        opt6_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt6_2ActionPerformed(evt);
            }
        });
        jPanel1.add(opt6_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 562, 288, -1));

        opt6_3.setOpaque(false);
        opt6_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt6_3ActionPerformed(evt);
            }
        });
        jPanel1.add(opt6_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 538, 373, -1));

        opt6_4.setOpaque(false);
        opt6_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt6_4ActionPerformed(evt);
            }
        });
        jPanel1.add(opt6_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 562, 373, -1));

        submit6.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        submit6.setText("Submit");
        submit6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit6ActionPerformed(evt);
            }
        });
        jPanel1.add(submit6, new org.netbeans.lib.awtextra.AbsoluteConstraints(708, 503, 138, -1));

        skip6.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        skip6.setText("Skip");
        skip6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                skip6ActionPerformed(evt);
            }
        });
        jPanel1.add(skip6, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 530, 138, -1));

        questarea7.setColumns(20);
        questarea7.setRows(5);
        jScrollPane8.setViewportView(questarea7);

        jPanel1.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 589, 663, 27));

        opt7_1.setOpaque(false);
        opt7_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt7_1ActionPerformed(evt);
            }
        });
        jPanel1.add(opt7_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 618, 285, -1));

        opt7_2.setOpaque(false);
        opt7_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt7_2ActionPerformed(evt);
            }
        });
        jPanel1.add(opt7_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 646, 284, -1));

        opt7_3.setOpaque(false);
        opt7_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt7_3ActionPerformed(evt);
            }
        });
        jPanel1.add(opt7_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 618, 361, -1));

        opt7_4.setOpaque(false);
        opt7_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt7_4ActionPerformed(evt);
            }
        });
        jPanel1.add(opt7_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 646, 361, -1));

        submit7.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        submit7.setText("Submit");
        submit7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit7ActionPerformed(evt);
            }
        });
        jPanel1.add(submit7, new org.netbeans.lib.awtextra.AbsoluteConstraints(708, 589, 138, -1));

        skip7.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        skip7.setText("Skip");
        skip7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                skip7ActionPerformed(evt);
            }
        });
        jPanel1.add(skip7, new org.netbeans.lib.awtextra.AbsoluteConstraints(708, 618, 138, -1));

        questarea8.setColumns(20);
        questarea8.setRows(5);
        jScrollPane9.setViewportView(questarea8);

        jPanel1.add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 669, 663, 27));

        submit8.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        submit8.setText("Submit");
        submit8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit8ActionPerformed(evt);
            }
        });
        jPanel1.add(submit8, new org.netbeans.lib.awtextra.AbsoluteConstraints(708, 669, 138, -1));

        skip8.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        skip8.setText("Skip");
        skip8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                skip8ActionPerformed(evt);
            }
        });
        jPanel1.add(skip8, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 700, 138, -1));

        opt8_4.setOpaque(false);
        opt8_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt8_4ActionPerformed(evt);
            }
        });
        jPanel1.add(opt8_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 719, 373, -1));

        opt8_3.setOpaque(false);
        opt8_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt8_3ActionPerformed(evt);
            }
        });
        jPanel1.add(opt8_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 698, 373, -1));

        opt8_2.setOpaque(false);
        opt8_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt8_2ActionPerformed(evt);
            }
        });
        jPanel1.add(opt8_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 719, 280, -1));

        opt8_1.setOpaque(false);
        opt8_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt8_1ActionPerformed(evt);
            }
        });
        jPanel1.add(opt8_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 698, 280, -1));

        questarea9.setColumns(20);
        questarea9.setRows(5);
        jScrollPane10.setViewportView(questarea9);

        jPanel1.add(jScrollPane10, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 747, 662, 28));

        opt9_1.setOpaque(false);
        opt9_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt9_1ActionPerformed(evt);
            }
        });
        jPanel1.add(opt9_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 781, 291, -1));

        opt9_2.setOpaque(false);
        opt9_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt9_2ActionPerformed(evt);
            }
        });
        jPanel1.add(opt9_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 806, 292, -1));

        opt9_3.setOpaque(false);
        opt9_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt9_3ActionPerformed(evt);
            }
        });
        jPanel1.add(opt9_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 781, 359, -1));

        opt9_4.setOpaque(false);
        opt9_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt9_4ActionPerformed(evt);
            }
        });
        jPanel1.add(opt9_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 806, 359, -1));

        submit9.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        submit9.setText("Submit");
        submit9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit9ActionPerformed(evt);
            }
        });
        jPanel1.add(submit9, new org.netbeans.lib.awtextra.AbsoluteConstraints(708, 747, 138, -1));

        skip9.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        skip9.setText("Skip");
        skip9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                skip9ActionPerformed(evt);
            }
        });
        jPanel1.add(skip9, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 780, 138, -1));

        questarea10.setColumns(20);
        questarea10.setRows(5);
        jScrollPane11.setViewportView(questarea10);

        jPanel1.add(jScrollPane11, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 829, 662, 31));

        opt10_1.setOpaque(false);
        opt10_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt10_1ActionPerformed(evt);
            }
        });
        jPanel1.add(opt10_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 866, 292, -1));

        opt10_2.setOpaque(false);
        opt10_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt10_2ActionPerformed(evt);
            }
        });
        jPanel1.add(opt10_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 891, 292, -1));

        opt10_3.setOpaque(false);
        opt10_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt10_3ActionPerformed(evt);
            }
        });
        jPanel1.add(opt10_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 866, 178, -1));

        next.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        next.setText("Next>>>");
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });
        jPanel1.add(next, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 870, 108, -1));

        opt10_4.setOpaque(false);
        opt10_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt10_4ActionPerformed(evt);
            }
        });
        jPanel1.add(opt10_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 891, 240, -1));

        submit10.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        submit10.setText("Submit");
        submit10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit10ActionPerformed(evt);
            }
        });
        jPanel1.add(submit10, new org.netbeans.lib.awtextra.AbsoluteConstraints(708, 829, 138, -1));

        skip10.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        skip10.setText("Skip");
        skip10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                skip10ActionPerformed(evt);
            }
        });
        jPanel1.add(skip10, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 860, 139, -1));

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 839, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 667, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void starttestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_starttestActionPerformed

        try
        {
            this.submit1.setEnabled(false);
            this.submit2.setEnabled(false);
            this.submit3.setEnabled(false);
            this.submit4.setEnabled(false);
            this.submit5.setEnabled(false);
            this.submit6.setEnabled(false);
            this.submit7.setEnabled(false);
            this.submit8.setEnabled(false);
            this.submit9.setEnabled(false);
            this.submit10.setEnabled(false);
            this.skip1.setEnabled(false);
            this.skip2.setEnabled(false);
            this.skip3.setEnabled(false);
            this.skip4.setEnabled(false);
            this.skip5.setEnabled(false);
            this.skip6.setEnabled(false);
            this.skip7.setEnabled(false);
            this.skip8.setEnabled(false);
            this.skip9.setEnabled(false);
            this.skip10.setEnabled(false);
            query="insert into Test(canROLLNO,format_Id)"+"values('"+rollno+"','"+fid+"')";
            cb.insertData(query);
            if(k<arrsize)
            {
                query="select QuestionDesc,1stOption,2ndOption,3rdOption,4thOption,crtOption from Question where cat_id='"+n[k]+"'";
                rset=cb.getData(query);
                while(rset.next())
                {
                    strar1[m]=rset.getString("QuestionDesc");
                    strar2[m]=rset.getString("1stOption");
                    strar3[m]=rset.getString("2ndOption");
                    strar4[m]=rset.getString("3rdOption");
                    strar5[m]=rset.getString("4thOption");
                    strar6[m]=rset.getString("crtOption");
                    System.out.println("dis:"+strar6[m]);
                    m++;
                }
                m=0;
                while(m<10)
                {
                    if(m==0)
                    {
                        this.questarea1.setText(strar1[m]);
                        this.opt_1.setText(strar2[m]);
                        this.opt_2.setText(strar3[m]);
                        this.opt_3.setText(strar4[m]);
                        this.opt_4.setText(strar5[m]);
                    }
                    else if(m==1)
                    {
                        this.questarea2.setText(strar1[m]);
                        this.opt2_1.setText(strar2[m]);
                        this.opt2_2.setText(strar3[m]);
                        this.opt2_3.setText(strar4[m]);
                        this.opt2_4.setText(strar5[m]);
                    }
                    else if(m==2)
                    {
                        this.questarea3.setText(strar1[m]);
                        this.opt3_1.setText(strar2[m]);
                        this.opt3_2.setText(strar3[m]);
                        this.opt3_3.setText(strar4[m]);
                        this.opt3_4.setText(strar5[m]);
                    }
                    else if(m==3)
                    {
                        this.questarea4.setText(strar1[m]);
                        this.opt4_1.setText(strar2[m]);
                        this.opt4_2.setText(strar3[m]);
                        this.opt4_3.setText(strar4[m]);
                        this.opt4_4.setText(strar5[m]);
                    }
                    else if(m==4)
                    {
                        this.questarea5.setText(strar1[m]);
                        this.opt5_1.setText(strar2[m]);
                        this.opt5_2.setText(strar3[m]);
                        this.opt5_3.setText(strar4[m]);
                        this.opt5_4.setText(strar5[m]);
                    }
                    else if(m==5)
                    {
                        this.questarea6.setText(strar1[m]);
                        this.opt6_1.setText(strar2[m]);
                        this.opt6_2.setText(strar3[m]);
                        this.opt6_3.setText(strar4[m]);
                        this.opt6_4.setText(strar5[m]);

                    }
                    else if(m==6)
                    {
                        this.questarea7.setText(strar1[m]);
                        this.opt7_1.setText(strar2[m]);
                        this.opt7_2.setText(strar3[m]);
                        this.opt7_3.setText(strar4[m]);
                        this.opt7_4.setText(strar5[m]);
                    }
                    else if(m==7)
                    {
                        this.questarea8.setText(strar1[m]);
                        this.opt8_1.setText(strar2[m]);
                        this.opt8_2.setText(strar3[m]);
                        this.opt8_3.setText(strar4[m]);
                        this.opt8_4.setText(strar5[m]);
                    }
                    else if(m==8)
                    {
                        this.questarea9.setText(strar1[m]);
                        this.opt9_1.setText(strar2[m]);
                        this.opt9_2.setText(strar3[m]);
                        this.opt9_3.setText(strar4[m]);
                        this.opt9_4.setText(strar5[m]);
                    }
                    else if(m==9)
                    {
                        this.questarea10.setText(strar1[m]);
                        this.opt10_1.setText(strar2[m]);
                        this.opt10_2.setText(strar3[m]);
                        this.opt10_3.setText(strar4[m]);
                        this.opt10_4.setText(strar5[m]);
                    }
                    m++;
                    counter++;
                }
                k++;

            }
            query="select TestTime from TestFormat where FormatId='"+fid+"'";
            rset=cb.getData(query);
            while(rset.next())
            {
                time=rset.getInt("TestTime");
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        new Thread(new Runnable() 
        {

            @Override
            public void run() 
            {
                int timer=time*60;
                int tam;
                while(true)
                {
                    if( timer % 60 == 0)
                    {
                        tam = 60;
                        time--;
                    }
                    else
                       tam = timer % 60;
                   if(tam == 60)
                       timerlbl.setText((time+1)+":"+"00");
                     else
                    {
                       if(tam>= 10)   
                           timerlbl.setText(time+" : "+tam);
                       else
                           timerlbl.setText(time+" : 0"+tam);
                    }
                   try 
                   {
                       Thread.sleep(1000);
                       timer--;
                       if(timer == 0 )
                       {
                          timerlbl.setText("00 : 00");
                          JOptionPane.showMessageDialog(null, "Time's up dude!");
                          Dispose();
                          break;
                       }
                       else if(is_completed== true)
                       {
                           JOptionPane.showMessageDialog(null,"Test Has Finished ");
                           Dispose();
                           break;
                       }
                   }
                   catch (InterruptedException | HeadlessException ex)
                   {
                       JOptionPane.showMessageDialog(null,ex.getMessage());
                   }
                }
            }
        }).start();
    }//GEN-LAST:event_starttestActionPerformed
public void Dispose()
{
    this.dispose();
}
    private void opt_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt_3ActionPerformed

        canans=this.opt_3.getText();
    }//GEN-LAST:event_opt_3ActionPerformed

    private void submit5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit5ActionPerformed

        if(canans!=null)
        {
         j++;
        this.opt5_1.setSelected(false);
        this.opt5_2.setSelected(false);
        this.opt5_3.setSelected(false);
        this.opt5_4.setSelected(false);
        try
        {
            query="insert into CompletedTest(canROLLNo,canAns,crtAns)"+"values('"+rollno+"','"+canans+"','"+strar6[j]+"')";
            cb.insertData(query);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
       
        System.out.println("ans:"+j);
        this.questarea5.setText("");
        this.opt5_1.setText("");
        this.opt5_2.setText("");
        this.opt5_3.setText("");
        this.opt5_4.setText("");
        }
        else
        {
             JOptionPane.showMessageDialog(null, "First select the option");
        }
    }//GEN-LAST:event_submit5ActionPerformed

    private void opt6_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt6_4ActionPerformed
       canans=this.opt6_4.getText();
    }//GEN-LAST:event_opt6_4ActionPerformed

    private void submit7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit7ActionPerformed

        if(canans!=null)
        {
         j++;
        this.opt7_1.setSelected(false);
        this.opt7_2.setSelected(false);
        this.opt7_3.setSelected(false);
        this.opt7_4.setSelected(false);
        try
        {
            query="insert into CompletedTest(canROLLNo,canAns,crtAns)"+"values('"+rollno+"','"+canans+"','"+strar6[j]+"')";
            cb.insertData(query);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        System.out.println("ans:"+j);
        this.questarea7.setText("");
        this.opt7_1.setText("");
        this.opt7_2.setText("");
        this.opt7_3.setText("");
        this.opt7_4.setText("");
        }
        else
        {
             JOptionPane.showMessageDialog(null, "First select the option");
        }
    }//GEN-LAST:event_submit7ActionPerformed

    private void opt8_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt8_2ActionPerformed
        canans=this.opt8_2.getText();
    }//GEN-LAST:event_opt8_2ActionPerformed

    private void opt9_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt9_3ActionPerformed
      canans=this.opt9_3.getText();
    }//GEN-LAST:event_opt9_3ActionPerformed

    private void opt10_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt10_3ActionPerformed
        canans=this.opt10_3.getText();
    }//GEN-LAST:event_opt10_3ActionPerformed

    private void opt10_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt10_4ActionPerformed
        canans=this.opt10_4.getText();
    }//GEN-LAST:event_opt10_4ActionPerformed

    private void submit10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit10ActionPerformed

        if(canans!=null)
        {
         j++;
        this.opt10_1.setSelected(false);
        this.opt10_2.setSelected(false);
        this.opt10_3.setSelected(false);
        this.opt10_4.setSelected(false);
        try
        {
            query="insert into CompletedTest(canROLLNo,canAns,crtAns)"+"values('"+rollno+"','"+canans+"','"+strar6[j]+"')";
            cb.insertData(query);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        if(j>=9)
            j=0;
        System.out.println("ans:"+j);
        this.questarea5.setText("");
        this.opt10_1.setText("");
        this.opt10_2.setText("");
        this.opt10_3.setText("");
        this.opt10_4.setText("");
        }
        else
        {
             JOptionPane.showMessageDialog(null, "First select the option");
        }
    }//GEN-LAST:event_submit10ActionPerformed

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed

        if(k<arrsize)
        {
            counter=0;
            m=0;
            try
            {
                query="select QuestionDesc,1stOption,2ndOption,3rdOption,4thOption,crtOption from Question where cat_id='"+n[k]+"'";
                rset=cb.getData(query);
                while(rset.next())
                {
                    strar1[m]=rset.getString("QuestionDesc");
                    strar2[m]=rset.getString("1stOption");
                    strar3[m]=rset.getString("2ndOption");
                    strar4[m]=rset.getString("3rdOption");
                    strar5[m]=rset.getString("4thOption");
                    strar6[m]=rset.getString("crtOption");
                    System.out.println("dis:"+strar6[m]);
                    m++;
                }
                m=0;
                while(m<10)
                {
                    if(m==0)
                    {
                        this.questarea1.setText(strar1[m]);
                        this.opt_1.setText(strar2[m]);
                        this.opt_2.setText(strar3[m]);
                        this.opt_3.setText(strar4[m]);
                        this.opt_4.setText(strar5[m]);
                    }
                    else if(m==1)
                    {
                        this.questarea2.setText(strar1[m]);
                        this.opt2_1.setText(strar2[m]);
                        this.opt2_2.setText(strar3[m]);
                        this.opt2_3.setText(strar4[m]);
                        this.opt2_4.setText(strar5[m]);
                    }
                    else if(m==2)
                    {
                        this.questarea3.setText(strar1[m]);
                        this.opt3_1.setText(strar2[m]);
                        this.opt3_2.setText(strar3[m]);
                        this.opt3_3.setText(strar4[m]);
                        this.opt3_4.setText(strar5[m]);
                    }
                    else if(m==3)
                    {
                        this.questarea4.setText(strar1[m]);
                        this.opt4_1.setText(strar2[m]);
                        this.opt4_2.setText(strar3[m]);
                        this.opt4_3.setText(strar4[m]);
                        this.opt4_4.setText(strar5[m]);
                    }
                    else if(m==4)
                    {
                        this.questarea5.setText(strar1[m]);
                        this.opt5_1.setText(strar2[m]);
                        this.opt5_2.setText(strar3[m]);
                        this.opt5_3.setText(strar4[m]);
                        this.opt5_4.setText(strar5[m]);
                    }
                    else if(m==5)
                    {
                        this.questarea6.setText(strar1[m]);
                        this.opt6_1.setText(strar2[m]);
                        this.opt6_2.setText(strar3[m]);
                        this.opt6_3.setText(strar4[m]);
                        this.opt6_4.setText(strar5[m]);

                    }
                    else if(m==6)
                    {
                        this.questarea7.setText(strar1[m]);
                        this.opt7_1.setText(strar2[m]);
                        this.opt7_2.setText(strar3[m]);
                        this.opt7_3.setText(strar4[m]);
                        this.opt7_4.setText(strar5[m]);
                    }
                    else if(m==7)
                    {
                        this.questarea8.setText(strar1[m]);
                        this.opt8_1.setText(strar2[m]);
                        this.opt8_2.setText(strar3[m]);
                        this.opt8_3.setText(strar4[m]);
                        this.opt8_4.setText(strar5[m]);
                    }
                    else if(m==8)
                    {
                        this.questarea9.setText(strar1[m]);
                        this.opt9_1.setText(strar2[m]);
                        this.opt9_2.setText(strar3[m]);
                        this.opt9_3.setText(strar4[m]);
                        this.opt9_4.setText(strar5[m]);
                    }
                    else if(m==9)
                    {
                        this.questarea10.setText(strar1[m]);
                        this.opt10_1.setText(strar2[m]);
                        this.opt10_2.setText(strar3[m]);
                        this.opt10_3.setText(strar4[m]);
                        this.opt10_4.setText(strar5[m]);
                    }
                    m++;
                    counter++;
                }
                arr=0;
                k++;
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "All submitted");
        }
    }//GEN-LAST:event_nextActionPerformed

    private void submit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit1ActionPerformed

        if(canans!=null)
        {
        this.opt_1.setSelected(false);
        this.opt_2.setSelected(false);
        this.opt_3.setSelected(false);
        this.opt_4.setSelected(false);
        try
        {
            query="insert into CompletedTest(canROLLNo,canAns,crtAns)"+"values('"+rollno+"','"+canans+"','"+strar6[j]+"')";
            cb.insertData(query);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        this.questarea1.setText("");
        this.opt_1.setText("");
        this.opt_2.setText("");
        this.opt_3.setText("");
        this.opt_4.setText("");
     System.out.println("ans:"+j);
        }
        else
        {
             JOptionPane.showMessageDialog(null, "First select the option");
        }
        
    }//GEN-LAST:event_submit1ActionPerformed

    private void opt_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt_1ActionPerformed

        canans=this.opt_1.getText();
    }//GEN-LAST:event_opt_1ActionPerformed

    private void opt_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt_2ActionPerformed

        canans=this.opt_2.getText();
    }//GEN-LAST:event_opt_2ActionPerformed

    private void opt_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt_4ActionPerformed

        canans=this.opt_4.getText();
    }//GEN-LAST:event_opt_4ActionPerformed

    private void opt2_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt2_1ActionPerformed
        canans=this.opt2_1.getText();
    }//GEN-LAST:event_opt2_1ActionPerformed

    private void opt2_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt2_2ActionPerformed

        canans=this.opt2_2.getText();
    }//GEN-LAST:event_opt2_2ActionPerformed

    private void opt2_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt2_3ActionPerformed

        canans=this.opt2_3.getText();
    }//GEN-LAST:event_opt2_3ActionPerformed

    private void opt2_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt2_4ActionPerformed

        canans=this.opt2_4.getText();
    }//GEN-LAST:event_opt2_4ActionPerformed

    private void opt3_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt3_1ActionPerformed
   
        canans=this.opt3_1.getText();
    }//GEN-LAST:event_opt3_1ActionPerformed

    private void opt3_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt3_2ActionPerformed
     canans=this.opt3_2.getText();
    }//GEN-LAST:event_opt3_2ActionPerformed

    private void opt3_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt3_3ActionPerformed

          canans=this.opt3_3.getText(); 
    }//GEN-LAST:event_opt3_3ActionPerformed

    private void opt3_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt3_4ActionPerformed

          canans=this.opt3_4.getText(); 
    }//GEN-LAST:event_opt3_4ActionPerformed

    private void opt4_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt4_1ActionPerformed

          canans=this.opt4_1.getText(); 
    }//GEN-LAST:event_opt4_1ActionPerformed

    private void opt4_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt4_2ActionPerformed

        canans=this.opt4_2.getText(); 
    }//GEN-LAST:event_opt4_2ActionPerformed

    private void opt4_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt4_3ActionPerformed
       canans=this.opt4_3.getText(); 
    }//GEN-LAST:event_opt4_3ActionPerformed

    private void opt4_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt4_4ActionPerformed

        canans=this.opt4_4.getText(); 
    }//GEN-LAST:event_opt4_4ActionPerformed

    private void opt5_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt5_1ActionPerformed
 
        canans=this.opt5_1.getText(); 
    }//GEN-LAST:event_opt5_1ActionPerformed

    private void opt5_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt5_2ActionPerformed

          canans=this.opt5_2.getText();
    }//GEN-LAST:event_opt5_2ActionPerformed

    private void opt5_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt5_3ActionPerformed

          canans=this.opt5_3.getText();
    }//GEN-LAST:event_opt5_3ActionPerformed

    private void opt5_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt5_4ActionPerformed
          canans=this.opt5_4.getText();
    }//GEN-LAST:event_opt5_4ActionPerformed

    private void opt6_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt6_1ActionPerformed
         canans=this.opt6_1.getText();
    }//GEN-LAST:event_opt6_1ActionPerformed

    private void opt6_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt6_2ActionPerformed
       canans=this.opt6_2.getText();
    }//GEN-LAST:event_opt6_2ActionPerformed

    private void opt6_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt6_3ActionPerformed
        canans=this.opt6_3.getText();
    }//GEN-LAST:event_opt6_3ActionPerformed

    private void opt7_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt7_1ActionPerformed
        canans=this.opt7_1.getText();
    }//GEN-LAST:event_opt7_1ActionPerformed

    private void opt7_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt7_2ActionPerformed
        canans=this.opt7_2.getText();
    }//GEN-LAST:event_opt7_2ActionPerformed

    private void opt7_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt7_3ActionPerformed
        canans=this.opt7_3.getText();
    }//GEN-LAST:event_opt7_3ActionPerformed

    private void opt7_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt7_4ActionPerformed
        canans=this.opt7_4.getText();
    }//GEN-LAST:event_opt7_4ActionPerformed

    private void opt8_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt8_1ActionPerformed
        canans=this.opt8_1.getText();
    }//GEN-LAST:event_opt8_1ActionPerformed

    private void opt8_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt8_3ActionPerformed
       canans=this.opt8_3.getText();
    }//GEN-LAST:event_opt8_3ActionPerformed

    private void opt8_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt8_4ActionPerformed
        canans=this.opt8_4.getText();
    }//GEN-LAST:event_opt8_4ActionPerformed

    private void opt9_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt9_1ActionPerformed
        canans=this.opt9_1.getText();
    }//GEN-LAST:event_opt9_1ActionPerformed

    private void opt9_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt9_2ActionPerformed
           canans=this.opt9_2.getText();
    }//GEN-LAST:event_opt9_2ActionPerformed

    private void opt9_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt9_4ActionPerformed
           canans=this.opt9_4.getText();
    }//GEN-LAST:event_opt9_4ActionPerformed

    private void opt10_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt10_1ActionPerformed
           canans=this.opt10_1.getText();
    }//GEN-LAST:event_opt10_1ActionPerformed

    private void opt10_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt10_2ActionPerformed
           canans=this.opt10_2.getText();
    }//GEN-LAST:event_opt10_2ActionPerformed

    private void submit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit2ActionPerformed

        if(canans!=null)
        {
        this.opt2_1.setSelected(false);
        this.opt2_2.setSelected(false);
        this.opt2_3.setSelected(false);
        this.opt2_4.setSelected(false);
        j++;
        try
        {
            query="insert into CompletedTest(canROLLNo,canAns,crtAns)"+"values('"+rollno+"','"+canans+"','"+strar6[j]+"')";
            cb.insertData(query);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        this.questarea2.setText("");
        this.opt2_1.setText("");
        this.opt2_2.setText("");
        this.opt2_3.setText("");
        this.opt2_4.setText("");
        System.out.println("ans:"+j);
        }
        else
        {
             JOptionPane.showMessageDialog(null, "First select the option");
        }
    }//GEN-LAST:event_submit2ActionPerformed

    private void submit3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit3ActionPerformed

        if(canans!=null)
        {
          j++;
        this.opt3_1.setSelected(false);
        this.opt3_2.setSelected(false);
        this.opt3_3.setSelected(false);
        this.opt3_4.setSelected(false);
        try
        {
            query="insert into CompletedTest(canROLLNo,canAns,crtAns)"+"values('"+rollno+"','"+canans+"','"+strar6[j]+"')";
            cb.insertData(query);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        this.questarea3.setText("");
        this.opt3_1.setText("");
        this.opt3_2.setText("");
        this.opt3_3.setText("");
        this.opt3_4.setText("");
        System.out.println("ans:"+j);
        }
        else
        {
              JOptionPane.showMessageDialog(null, "First select the option");
        }
    }//GEN-LAST:event_submit3ActionPerformed

    private void submit4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit4ActionPerformed

        if(canans!=null)
        {
        j++;
        this.opt4_1.setSelected(false);
        this.opt4_2.setSelected(false);
        this.opt4_3.setSelected(false);
        this.opt4_4.setSelected(false);
        try
        {
            query="insert into CompletedTest(canROLLNo,canAns,crtAns)"+"values('"+rollno+"','"+canans+"','"+strar6[j]+"')";
            cb.insertData(query);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        System.out.println("ans:"+j);
        this.questarea4.setText("");
        this.opt4_1.setText("");
        this.opt4_2.setText("");
        this.opt4_3.setText("");
        this.opt4_4.setText("");
        }
        else
        {
              JOptionPane.showMessageDialog(null, "You have selected the option to submit press Submit button");
        }
    }//GEN-LAST:event_submit4ActionPerformed

    private void submit6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit6ActionPerformed

        if(canans!=null)
        {
         j++;
        this.opt6_1.setSelected(false);
        this.opt6_2.setSelected(false);
        this.opt6_3.setSelected(false);
        this.opt6_4.setSelected(false);
        try
        {
            query="insert into CompletedTest(canROLLNo,canAns,crtAns)"+"values('"+rollno+"','"+canans+"','"+strar6[j]+"')";
            cb.insertData(query);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        System.out.println("ans:"+j);
        this.questarea6.setText("");
        this.opt6_1.setText("");
        this.opt6_2.setText("");
        this.opt6_3.setText("");
        this.opt6_4.setText("");
        }
        else
        {
              JOptionPane.showMessageDialog(null, "You have selected the option to submit press Submit button");
        }
    }//GEN-LAST:event_submit6ActionPerformed

    private void submit8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit8ActionPerformed

        if(canans!=null)
        {
         j++;
        this.opt8_1.setSelected(false);
        this.opt8_2.setSelected(false);
        this.opt8_3.setSelected(false);
        this.opt8_4.setSelected(false);
        try
        {
            query="insert into CompletedTest(canROLLNo,canAns,crtAns)"+"values('"+rollno+"','"+canans+"','"+strar6[j]+"')";
            cb.insertData(query);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        System.out.println("ans:"+j);
        this.questarea5.setText("");
        this.opt8_1.setText("");
        this.opt8_2.setText("");
        this.opt8_3.setText("");
        this.opt8_4.setText("");
        }
        else
        {
              JOptionPane.showMessageDialog(null, "You have selected the option to submit press Submit button");
        }
    }//GEN-LAST:event_submit8ActionPerformed

    private void submit9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit9ActionPerformed

        if(canans!=null)
        {
         j++;
        this.opt9_1.setSelected(false);
        this.opt9_2.setSelected(false);
        this.opt9_3.setSelected(false);
        this.opt9_4.setSelected(false);
        try
        {
            query="insert into CompletedTest(canROLLNo,canAns,crtAns)"+"values('"+rollno+"','"+canans+"','"+strar6[j]+"')";
            cb.insertData(query);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        System.out.println("ans:"+j);
        this.questarea9.setText("");
        this.opt9_1.setText("");
        this.opt9_2.setText("");
        this.opt9_3.setText("");
        this.opt9_4.setText("");
        }
        else
        {
              JOptionPane.showMessageDialog(null, "First Select the option");
        }
    }//GEN-LAST:event_submit9ActionPerformed

    private void skip1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_skip1ActionPerformed

        if(canans!=null)
        {
        str1=this.questarea1.getText();
        str2=this.opt_1.getText();
        str3=this.opt_2.getText();
        str4=this.opt_3.getText();
        str5=this.opt_4.getText();
        this.questarea1.setText("");
        this.opt_1.setText("");
        this.opt_2.setText("");
        this.opt_3.setText("");
        this.opt_4.setText("");

        try 
        {
            query="select QuestionId from Question where QuestionDesc='"+str1+"'";
            rset=cb.getData(query);
            while(rset.next())
            {
               questid=rset.getInt("QuestionId");
            }
            query="select TestId from Test where canRollNo='"+rollno+"'";
            rset=cb.getData(query);
            while(rset.next())
            {
                testid=rset.getInt("TestId");
            }
            query="insert into SkipedQuestion(QuestionId,QuestionDesc,1stOption,2ndOption,3rdOption,4thOption,TestId)"+"values('"+questid+"','"+str1+"','"+str2+"','"+str3+"','"+str4+"','"+str5+"','"+testid+"')";
            cb.insertData(query);
            System.out.println("Successfully saved");
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        j++;
        }
        else
        {
              JOptionPane.showMessageDialog(null, "You have selected the option to submit press Submit button");
        }
    }//GEN-LAST:event_skip1ActionPerformed

    private void skip2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_skip2ActionPerformed
      
        if(canans!=null)
        {
        str1=this.questarea2.getText();
        str2=this.opt2_1.getText();
        str3=this.opt2_2.getText();
        str4=this.opt2_3.getText();
        str5=this.opt2_4.getText();
        this.questarea2.setText("");
        this.opt2_1.setText("");
        this.opt2_2.setText("");
        this.opt2_3.setText("");
        this.opt2_4.setText("");

        try 
        {
            query="select QuestionId from Question where QuestionDesc='"+str1+"'";
            rset=cb.getData(query);
            while(rset.next())
            {
               questid=rset.getInt("QuestionId");
            }
            query="select TestId from Test where canRollNo='"+rollno+"'";
            rset=cb.getData(query);
            while(rset.next())
            {
                testid=rset.getInt("TestId");
            }
            query="insert into SkipedQuestion(QuestionId,QuestionDesc,1stOption,2ndOption,3rdOption,4thOption,TestId)"+"values('"+questid+"','"+str1+"','"+str2+"','"+str3+"','"+str4+"','"+str5+"','"+testid+"')";
            cb.insertData(query);
            System.out.println("Successfully saved");
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        j++;
        }
        else
        {
              JOptionPane.showMessageDialog(null, "You have selected the option to submit press Submit button");
        }
        

    }//GEN-LAST:event_skip2ActionPerformed

    private void skip3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_skip3ActionPerformed

        if(canans!=null)
        {
         str1=this.questarea3.getText();
        str2=this.opt3_1.getText();
        str3=this.opt3_2.getText();
        str4=this.opt3_3.getText();
        str5=this.opt3_4.getText();
        this.questarea3.setText("");
        this.opt3_1.setText("");
        this.opt3_2.setText("");
        this.opt3_3.setText("");
        this.opt3_4.setText("");

        try 
        {
            query="select QuestionId from Question where QuestionDesc='"+str1+"'";
            rset=cb.getData(query);
            while(rset.next())
            {
               questid=rset.getInt("QuestionId");
            }
            query="select TestId from Test where canRollNo='"+rollno+"'";
            rset=cb.getData(query);
            while(rset.next())
            {
                testid=rset.getInt("TestId");
            }
            query="insert into SkipedQuestion(QuestionId,QuestionDesc,1stOption,2ndOption,3rdOption,4thOption,TestId)"+"values('"+questid+"','"+str1+"','"+str2+"','"+str3+"','"+str4+"','"+str5+"','"+testid+"')";
            cb.insertData(query);
            System.out.println("Successfully saved");
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        j++;
        }
        else
        {
              JOptionPane.showMessageDialog(null, "You have selected the option to submit press Submit button");
        }
    }//GEN-LAST:event_skip3ActionPerformed

    private void skip4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_skip4ActionPerformed
       if(canans!=null)
       {
        str1=this.questarea4.getText();
        str2=this.opt4_1.getText();
        str3=this.opt4_2.getText();
        str4=this.opt4_3.getText();
        str5=this.opt4_4.getText();
        this.questarea4.setText("");
        this.opt4_1.setText("");
        this.opt4_2.setText("");
        this.opt4_3.setText("");
        this.opt4_4.setText("");

        try 
        {
           query="select QuestionId from Question where QuestionDesc='"+str1+"'";
           rset=cb.getData(query);
            while(rset.next())
            {
               questid=rset.getInt("QuestionId");
            }
            query="select TestId from Test where canRollNo='"+rollno+"'";
            rset=cb.getData(query);
            while(rset.next())
            {
                testid=rset.getInt("TestId");
            }
            query="insert into SkipedQuestion(QuestionId,QuestionDesc,1stOption,2ndOption,3rdOption,4thOption,TestId)"+"values('"+questid+"','"+str1+"','"+str2+"','"+str3+"','"+str4+"','"+str5+"','"+testid+"')";
            cb.insertData(query);
            System.out.println("Successfully saved");
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        j++;
       }
       else
       {
             JOptionPane.showMessageDialog(null, "You have selected the option to submit press Submit button");
       }
    }//GEN-LAST:event_skip4ActionPerformed

    private void skip5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_skip5ActionPerformed
        if(canans!=null)
        {
        str1=this.questarea5.getText();
        str2=this.opt5_1.getText();
        str3=this.opt5_2.getText();
        str4=this.opt5_3.getText();
        str5=this.opt5_4.getText();
        this.questarea5.setText("");
        this.opt5_1.setText("");
        this.opt5_2.setText("");
        this.opt5_3.setText("");
        this.opt5_4.setText("");
        try 
        {
           query="select QuestionId from Question where QuestionDesc='"+str1+"'";
           cb.getData(query);
            while(rset.next())
            {
               questid=rset.getInt("QuestionId");
            }
            query="select TestId from Test where canRollNo='"+rollno+"'";
            cb.getData(query);
            while(rset.next())
            {
                testid=rset.getInt("TestId");
            }
            query="insert into SkipedQuestion(QuestionId,QuestionDesc,1stOption,2ndOption,3rdOption,4thOption,TestId)"+"values('"+questid+"','"+str1+"','"+str2+"','"+str3+"','"+str4+"','"+str5+"','"+testid+"')";
            cb.insertData(query);
            System.out.println("Successfully saved");
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        j++;
        }
        else
        {
              JOptionPane.showMessageDialog(null, "You have selected the option to submit press Submit button");
        }
    }//GEN-LAST:event_skip5ActionPerformed

    private void skip6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_skip6ActionPerformed
        if(canans!=null)
        {
        str1=this.questarea6.getText();
        str2=this.opt6_1.getText();
        str3=this.opt6_2.getText();
        str4=this.opt6_3.getText();
        str5=this.opt6_4.getText();
        this.questarea6.setText("");
        this.opt6_1.setText("");
        this.opt6_2.setText("");
        this.opt6_3.setText("");
        this.opt6_4.setText("");
        try 
        {
            query="select QuestionId from Question where QuestionDesc='"+str1+"'";
            rset=cb.getData(query);
            while(rset.next())
            {
               questid=rset.getInt("QuestionId");
            }
            query="select TestId from Test where canRollNo='"+rollno+"'";
            rset=cb.getData(query);
            while(rset.next())
            {
                testid=rset.getInt("TestId");
            }
            query="insert into SkipedQuestion(QuestionId,QuestionDesc,1stOption,2ndOption,3rdOption,4thOption,TestId)"+"values('"+questid+"','"+str1+"','"+str2+"','"+str3+"','"+str4+"','"+str5+"','"+testid+"')";
            cb.insertData(query);
            System.out.println("Successfully saved");
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        j++;
        }
        else
        {
              JOptionPane.showMessageDialog(null, "You have selected the option to submit press Submit button");
        }

    }//GEN-LAST:event_skip6ActionPerformed

    private void skip7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_skip7ActionPerformed
        if(canans!=null)
        {
        str1=this.questarea7.getText();
        str2=this.opt7_1.getText();
        str3=this.opt7_2.getText();
        str4=this.opt7_3.getText();
        str5=this.opt7_4.getText();
        this.questarea7.setText("");
        this.opt7_1.setText("");
        this.opt7_2.setText("");
        this.opt7_3.setText("");
        this.opt7_4.setText("");
        try 
        {
            query="select QuestionId from Question where QuestionDesc='"+str1+"'";
            rset=cb.getData(query);
            while(rset.next())
            {
               questid=rset.getInt("QuestionId");
            }
            query="select TestId from Test where canRollNo='"+rollno+"'";
            rset=cb.getData(query);
            while(rset.next())
            {
                testid=rset.getInt("TestId");
            }
            query="insert into SkipedQuestion(QuestionId,QuestionDesc,1stOption,2ndOption,3rdOption,4thOption,TestId)"+"values('"+questid+"','"+str1+"','"+str2+"','"+str3+"','"+str4+"','"+str5+"','"+testid+"')";
            cb.insertData(query);
            System.out.println("Successfully saved");
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        j++;
        }
        else
        {
           JOptionPane.showMessageDialog(null, "You have selected the option to submit press Submit button");
        }

    }//GEN-LAST:event_skip7ActionPerformed

    private void skip8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_skip8ActionPerformed
        if(canans!=null)
        {
        str1=this.questarea8.getText();
        str2=this.opt8_1.getText();
        str3=this.opt8_2.getText();
        str4=this.opt8_3.getText();
        str5=this.opt8_4.getText();
        this.questarea8.setText("");
        this.opt8_1.setText("");
        this.opt8_2.setText("");
        this.opt8_3.setText("");
        this.opt8_4.setText("");
        try 
        {
            query="select QuestionId from Question where QuestionDesc='"+str1+"'";
            rset=cb.getData(query);
            while(rset.next())
            {
               questid=rset.getInt("QuestionId");
            }
            query="select TestId from Test where canRollNo='"+rollno+"'";
            rset=cb.getData(query);
            while(rset.next())
            {
                testid=rset.getInt("TestId");
            }
            query="insert into SkipedQuestion(QuestionId,QuestionDesc,1stOption,2ndOption,3rdOption,4thOption,TestId)"+"values('"+questid+"','"+str1+"','"+str2+"','"+str3+"','"+str4+"','"+str5+"','"+testid+"')";
            rset=cb.getData(query);
            System.out.println("Successfully saved");
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        j++;
        }
        else
        {
           JOptionPane.showMessageDialog(null, "You have selected the option to submit press Submit button");
        }

    }//GEN-LAST:event_skip8ActionPerformed

    private void skip9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_skip9ActionPerformed
        if(canans!=null)
        {
        str1=this.questarea9.getText();
        str2=this.opt9_1.getText();
        str3=this.opt9_2.getText();
        str4=this.opt9_3.getText();
        str5=this.opt9_4.getText();
        this.questarea9.setText("");
        this.opt9_1.setText("");
        this.opt9_2.setText("");
        this.opt9_3.setText("");
        this.opt9_4.setText("");
        try 
        {
            query="select QuestionId from Question where QuestionDesc='"+str1+"'";
            rset=cb.getData(query);
            while(rset.next())
            {
               questid=rset.getInt("QuestionId");
            }
            query="select TestId from Test where canRollNo='"+rollno+"'";
            rset=cb.getData(query);
            while(rset.next())
            {
                testid=rset.getInt("TestId");
            }
            query="insert into SkipedQuestion(QuestionId,QuestionDesc,1stOption,2ndOption,3rdOption,4thOption,TestId)"+"values('"+questid+"','"+str1+"','"+str2+"','"+str3+"','"+str4+"','"+str5+"','"+testid+"')";
            cb.insertData(query);
            System.out.println("Successfully saved");
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        j++;
        }
        else
        {
              JOptionPane.showMessageDialog(null, "You have selected the option to submit press Submit button");
        }

    }//GEN-LAST:event_skip9ActionPerformed

    private void skip10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_skip10ActionPerformed
        if(canans!=null)
        {
        str1=this.questarea10.getText();
        str2=this.opt10_1.getText();
        str3=this.opt10_2.getText();
        str4=this.opt10_3.getText();
        str5=this.opt10_4.getText();
        this.questarea10.setText("");
        this.opt10_1.setText("");
        this.opt10_2.setText("");
        this.opt10_3.setText("");
        this.opt10_4.setText("");
        try 
        {
            query="select QuestionId from Question where QuestionDesc='"+str1+"'";
            rset=cb.getData(query);
            while(rset.next())
            {
               questid=rset.getInt("QuestionId");
            }
            query="select TestId from Test where canRollNo='"+rollno+"'";
            rset=cb.getData(query);
            while(rset.next())
            {
                testid=rset.getInt("TestId");
            }
            query="insert into SkipedQuestion(QuestionId,QuestionDesc,1stOption,2ndOption,3rdOption,4thOption,TestId)"+"values('"+questid+"','"+str1+"','"+str2+"','"+str3+"','"+str4+"','"+str5+"','"+testid+"')";
            rset=cb.getData(query);
            System.out.println("Successfully saved");
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        j++;
        if (j>=9)
            j=0;
        }
        else
        {
              JOptionPane.showMessageDialog(null, "You have selected the option to submit press Submit button");
        }

    }//GEN-LAST:event_skip10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TenQuestions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TenQuestions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TenQuestions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TenQuestions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TenQuestions().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JButton next;
    private javax.swing.JRadioButton opt10_1;
    private javax.swing.JRadioButton opt10_2;
    private javax.swing.JRadioButton opt10_3;
    private javax.swing.JRadioButton opt10_4;
    private javax.swing.JRadioButton opt2_1;
    private javax.swing.JRadioButton opt2_2;
    private javax.swing.JRadioButton opt2_3;
    private javax.swing.JRadioButton opt2_4;
    private javax.swing.JRadioButton opt3_1;
    private javax.swing.JRadioButton opt3_2;
    private javax.swing.JRadioButton opt3_3;
    private javax.swing.JRadioButton opt3_4;
    private javax.swing.JRadioButton opt4_1;
    private javax.swing.JRadioButton opt4_2;
    private javax.swing.JRadioButton opt4_3;
    private javax.swing.JRadioButton opt4_4;
    private javax.swing.JRadioButton opt5_1;
    private javax.swing.JRadioButton opt5_2;
    private javax.swing.JRadioButton opt5_3;
    private javax.swing.JRadioButton opt5_4;
    private javax.swing.JRadioButton opt6_1;
    private javax.swing.JRadioButton opt6_2;
    private javax.swing.JRadioButton opt6_3;
    private javax.swing.JRadioButton opt6_4;
    private javax.swing.JRadioButton opt7_1;
    private javax.swing.JRadioButton opt7_2;
    private javax.swing.JRadioButton opt7_3;
    private javax.swing.JRadioButton opt7_4;
    private javax.swing.JRadioButton opt8_1;
    private javax.swing.JRadioButton opt8_2;
    private javax.swing.JRadioButton opt8_3;
    private javax.swing.JRadioButton opt8_4;
    private javax.swing.JRadioButton opt9_1;
    private javax.swing.JRadioButton opt9_2;
    private javax.swing.JRadioButton opt9_3;
    private javax.swing.JRadioButton opt9_4;
    private javax.swing.JRadioButton opt_1;
    private javax.swing.JRadioButton opt_2;
    private javax.swing.JRadioButton opt_3;
    private javax.swing.JRadioButton opt_4;
    private javax.swing.JTextArea questarea1;
    private javax.swing.JTextArea questarea10;
    private javax.swing.JTextArea questarea2;
    private javax.swing.JTextArea questarea3;
    private javax.swing.JTextArea questarea4;
    private javax.swing.JTextArea questarea5;
    private javax.swing.JTextArea questarea6;
    private javax.swing.JTextArea questarea7;
    private javax.swing.JTextArea questarea8;
    private javax.swing.JTextArea questarea9;
    private javax.swing.JButton skip1;
    private javax.swing.JButton skip10;
    private javax.swing.JButton skip2;
    private javax.swing.JButton skip3;
    private javax.swing.JButton skip4;
    private javax.swing.JButton skip5;
    private javax.swing.JButton skip6;
    private javax.swing.JButton skip7;
    private javax.swing.JButton skip8;
    private javax.swing.JButton skip9;
    private javax.swing.JButton starttest;
    private javax.swing.JButton submit1;
    private javax.swing.JButton submit10;
    private javax.swing.JButton submit2;
    private javax.swing.JButton submit3;
    private javax.swing.JButton submit4;
    private javax.swing.JButton submit5;
    private javax.swing.JButton submit6;
    private javax.swing.JButton submit7;
    private javax.swing.JButton submit8;
    private javax.swing.JButton submit9;
    private javax.swing.JLabel timerlbl;
    // End of variables declaration//GEN-END:variables
}
