/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project.deliverable;

/**
 *
 * @author Muhammad Junaid Tari
 */
public class UserMaintainer extends javax.swing.JFrame {
    private AddCandidate adcan;
    private AddTestSetter adtestset;
    private AddQuestSetter adquestset;
    public UserMaintainer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        add_questset = new javax.swing.JButton();
        add_candidate = new javax.swing.JButton();
        add_testset = new javax.swing.JButton();
        exit_um = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        add_questset.setText("Add Question Setter");
        add_questset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_questsetActionPerformed(evt);
            }
        });

        add_candidate.setText("Add Candidate");
        add_candidate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_candidateActionPerformed(evt);
            }
        });

        add_testset.setText("Add Test Setter");
        add_testset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_testsetActionPerformed(evt);
            }
        });

        exit_um.setText("Exit");
        exit_um.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit_umActionPerformed(evt);
            }
        });

        jLabel1.setText("                           Welcome to User Maintainer Log");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(add_candidate, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(add_questset, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                        .addComponent(add_testset, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exit_um, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(217, 217, 217))
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(105, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addComponent(add_candidate)
                .addGap(31, 31, 31)
                .addComponent(add_testset)
                .addGap(27, 27, 27)
                .addComponent(add_questset)
                .addGap(35, 35, 35)
                .addComponent(exit_um)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void add_candidateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_candidateActionPerformed
     adcan=new AddCandidate();
     adcan.setVisible(true);
     adcan.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_add_candidateActionPerformed

    private void add_testsetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_testsetActionPerformed
     adtestset=new AddTestSetter();
     adtestset.setVisible(true);
     adtestset.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_add_testsetActionPerformed

    private void add_questsetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_questsetActionPerformed
     adquestset=new AddQuestSetter();
     adquestset.setVisible(true);
     adquestset.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_add_questsetActionPerformed

    private void exit_umActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit_umActionPerformed
     this.setVisible(false);
    }//GEN-LAST:event_exit_umActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserMaintainer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserMaintainer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserMaintainer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserMaintainer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserMaintainer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_candidate;
    private javax.swing.JButton add_questset;
    private javax.swing.JButton add_testset;
    private javax.swing.JButton exit_um;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
