/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project.deliverable;


import connection.database.ConnectDatabase;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Muhammad Junaid Tari
 */
public class ViewFiveQuestions extends javax.swing.JFrame {

    ResultSet rset=null;
    int rollno;
    String deg;
    String canans;
    int fid;
    int l=0;
    int m=0;
    int k=0;
    int arr=0;
    int time;
    int arrsize;
    int counter;
    int j=0;
    int []n=new int[10];
    String []strar1=new String[10];
    String []strar2=new String[10];
    String []strar3=new String[10];
    String []strar4=new String[10];
    String []strar5=new String[10];
    String []strar6=new String[10];
    String str1;
    String str2;
    String str3;
    String str4;
    String str5;
    int questid;
    int testid;
    String query;
    boolean is_completed=false;
    ConnectDatabase cb=new ConnectDatabase();
    public ViewFiveQuestions() {
        initComponents();
        rollno=Candidate_Login.rno;
        this.submit1.setEnabled(false);
        this.submit2.setEnabled(false);
        this.submit3.setEnabled(false);
        this.submit4.setEnabled(false);
        this.submit5.setEnabled(false);
        this.skip1.setEnabled(false);
        this.skip2.setEnabled(false);
        this.skip3.setEnabled(false);
        this.skip4.setEnabled(false);
        this.skip5.setEnabled(false);
        try
        {   
         
           query="Select Degree from Candidate where ROLLNO='"+rollno+"'";
            rset=cb.getData(query);
            while(rset.next())
            {
               deg= rset.getString("Degree");
               //System.out.println("out:"+deg);

            }
            query="Select FormatId from TestFormat where Degree='"+deg+"'";
            rset=cb.getData(query);
            while(rset.next())
            {
                fid=rset.getInt("FormatId");
                // System.out.println("out:"+fid);
            }
            query="Select CategoryId from FormatCategory where Format_id='"+fid+"'";
            rset=cb.getData(query);
            while(rset.next())
            {
                n[l]=rset.getInt("CategoryId");
                //System.out.println("rset:"+n[l]);
                l++;
            }
            arrsize=l;
            
            
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea5 = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        questarea1 = new javax.swing.JTextArea();
        opt_1 = new javax.swing.JRadioButton();
        opt_2 = new javax.swing.JRadioButton();
        opt_3 = new javax.swing.JRadioButton();
        opt_4 = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        questarea2 = new javax.swing.JTextArea();
        opt2_1 = new javax.swing.JRadioButton();
        opt2_2 = new javax.swing.JRadioButton();
        opt2_3 = new javax.swing.JRadioButton();
        opt2_4 = new javax.swing.JRadioButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        questarea3 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        questarea4 = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        questarea5 = new javax.swing.JTextArea();
        opt3_1 = new javax.swing.JRadioButton();
        opt3_2 = new javax.swing.JRadioButton();
        opt3_3 = new javax.swing.JRadioButton();
        opt3_4 = new javax.swing.JRadioButton();
        opt4_1 = new javax.swing.JRadioButton();
        opt4_2 = new javax.swing.JRadioButton();
        opt4_3 = new javax.swing.JRadioButton();
        opt4_4 = new javax.swing.JRadioButton();
        opt5_1 = new javax.swing.JRadioButton();
        opt5_2 = new javax.swing.JRadioButton();
        starttest = new javax.swing.JButton();
        timerlbl = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        submit1 = new javax.swing.JButton();
        skip1 = new javax.swing.JButton();
        submit2 = new javax.swing.JButton();
        skip2 = new javax.swing.JButton();
        submit3 = new javax.swing.JButton();
        skip3 = new javax.swing.JButton();
        submit4 = new javax.swing.JButton();
        skip4 = new javax.swing.JButton();
        submit5 = new javax.swing.JButton();
        skip5 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        opt5_3 = new javax.swing.JRadioButton();
        opt5_4 = new javax.swing.JRadioButton();
        next = new javax.swing.JButton();

        jTextArea5.setColumns(20);
        jTextArea5.setRows(5);
        jScrollPane5.setViewportView(jTextArea5);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(350, 50));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        questarea1.setColumns(20);
        questarea1.setRows(5);
        jScrollPane1.setViewportView(questarea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 69, 643, 45));

        opt_1.setOpaque(false);
        opt_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt_1ActionPerformed(evt);
            }
        });
        getContentPane().add(opt_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 128, 291, -1));

        opt_2.setOpaque(false);
        opt_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt_2ActionPerformed(evt);
            }
        });
        getContentPane().add(opt_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 149, 291, -1));

        opt_3.setOpaque(false);
        opt_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt_3ActionPerformed(evt);
            }
        });
        getContentPane().add(opt_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 128, 290, -1));

        opt_4.setOpaque(false);
        opt_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt_4ActionPerformed(evt);
            }
        });
        getContentPane().add(opt_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 149, 313, -1));

        questarea2.setColumns(20);
        questarea2.setRows(5);
        jScrollPane2.setViewportView(questarea2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 172, 643, 45));

        opt2_1.setOpaque(false);
        opt2_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt2_1ActionPerformed(evt);
            }
        });
        getContentPane().add(opt2_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 219, 256, -1));

        opt2_2.setOpaque(false);
        opt2_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt2_2ActionPerformed(evt);
            }
        });
        getContentPane().add(opt2_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 240, 282, -1));

        opt2_3.setOpaque(false);
        opt2_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt2_3ActionPerformed(evt);
            }
        });
        getContentPane().add(opt2_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(331, 219, 289, -1));

        opt2_4.setOpaque(false);
        opt2_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt2_4ActionPerformed(evt);
            }
        });
        getContentPane().add(opt2_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(331, 240, 244, -1));

        questarea3.setColumns(20);
        questarea3.setRows(5);
        jScrollPane3.setViewportView(questarea3);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 263, 643, 45));

        questarea4.setColumns(20);
        questarea4.setRows(5);
        jScrollPane4.setViewportView(questarea4);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 362, 633, 45));

        questarea5.setColumns(20);
        questarea5.setRows(5);
        jScrollPane6.setViewportView(questarea5);

        getContentPane().add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 454, 633, 45));

        opt3_1.setOpaque(false);
        opt3_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt3_1ActionPerformed(evt);
            }
        });
        getContentPane().add(opt3_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 310, 264, -1));

        opt3_2.setOpaque(false);
        opt3_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt3_2ActionPerformed(evt);
            }
        });
        getContentPane().add(opt3_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 334, 273, -1));

        opt3_3.setOpaque(false);
        opt3_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt3_3ActionPerformed(evt);
            }
        });
        getContentPane().add(opt3_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(333, 310, 289, -1));

        opt3_4.setOpaque(false);
        opt3_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt3_4ActionPerformed(evt);
            }
        });
        getContentPane().add(opt3_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(333, 334, 289, 17));

        opt4_1.setOpaque(false);
        opt4_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt4_1ActionPerformed(evt);
            }
        });
        getContentPane().add(opt4_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 407, 313, -1));

        opt4_2.setOpaque(false);
        opt4_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt4_2ActionPerformed(evt);
            }
        });
        getContentPane().add(opt4_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 431, 313, -1));

        opt4_3.setOpaque(false);
        getContentPane().add(opt4_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(337, 407, 281, -1));

        opt4_4.setOpaque(false);
        opt4_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt4_4ActionPerformed(evt);
            }
        });
        getContentPane().add(opt4_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(337, 431, 282, -1));

        opt5_1.setOpaque(false);
        opt5_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt5_1ActionPerformed(evt);
            }
        });
        getContentPane().add(opt5_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 510, 288, -1));

        opt5_2.setOpaque(false);
        opt5_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt5_2ActionPerformed(evt);
            }
        });
        getContentPane().add(opt5_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 540, 302, -1));

        starttest.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        starttest.setText("Start");
        starttest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                starttestActionPerformed(evt);
            }
        });
        getContentPane().add(starttest, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 32, 91, -1));

        timerlbl.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        timerlbl.setText("Timer");
        getContentPane().add(timerlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 30, 68, 22));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 0, 141, 14));

        submit1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        submit1.setText("Submit");
        submit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit1ActionPerformed(evt);
            }
        });
        getContentPane().add(submit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(649, 69, -1, -1));

        skip1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        skip1.setText("Skip");
        skip1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                skip1ActionPerformed(evt);
            }
        });
        getContentPane().add(skip1, new org.netbeans.lib.awtextra.AbsoluteConstraints(649, 102, 65, -1));

        submit2.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        submit2.setText("Submit");
        submit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit2ActionPerformed(evt);
            }
        });
        getContentPane().add(submit2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 170, -1, -1));

        skip2.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        skip2.setText("Skip");
        skip2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                skip2ActionPerformed(evt);
            }
        });
        getContentPane().add(skip2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 200, 65, -1));

        submit3.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        submit3.setText("Submit");
        submit3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit3ActionPerformed(evt);
            }
        });
        getContentPane().add(submit3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 270, -1, -1));

        skip3.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        skip3.setText("Skip");
        skip3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                skip3ActionPerformed(evt);
            }
        });
        getContentPane().add(skip3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 300, 65, -1));

        submit4.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        submit4.setText("Submit");
        submit4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit4ActionPerformed(evt);
            }
        });
        getContentPane().add(submit4, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 370, -1, -1));

        skip4.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        skip4.setText("Skip");
        skip4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                skip4ActionPerformed(evt);
            }
        });
        getContentPane().add(skip4, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 400, 65, -1));

        submit5.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        submit5.setText("Submit");
        submit5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit5ActionPerformed(evt);
            }
        });
        getContentPane().add(submit5, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 460, -1, -1));

        skip5.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        skip5.setText("Skip");
        skip5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                skip5ActionPerformed(evt);
            }
        });
        getContentPane().add(skip5, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 490, 65, -1));

        jLabel2.setFont(new java.awt.Font("Algerian", 0, 24)); // NOI18N
        jLabel2.setText("Not Failure but low aim is a  crime");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel3.setText("Time Left :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 30, 100, -1));

        jPanel1.setBackground(new java.awt.Color(0, 51, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        opt5_3.setOpaque(false);
        opt5_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt5_3ActionPerformed(evt);
            }
        });
        jPanel1.add(opt5_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 510, 289, -1));

        opt5_4.setOpaque(false);
        opt5_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt5_4ActionPerformed(evt);
            }
        });
        jPanel1.add(opt5_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 540, 289, -1));

        next.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        next.setText("Next-->-->-->");
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });
        jPanel1.add(next, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 570, 116, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void opt4_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt4_2ActionPerformed
        canans=this.opt4_2.getText();
    }//GEN-LAST:event_opt4_2ActionPerformed

    private void starttestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_starttestActionPerformed

        try 
        {
        this.submit1.setEnabled(true);
        this.submit2.setEnabled(true);
        this.submit3.setEnabled(true);
        this.submit4.setEnabled(true);
        this.submit5.setEnabled(true);
        this.skip1.setEnabled(true);
        this.skip2.setEnabled(true);
        this.skip3.setEnabled(true);
        this.skip4.setEnabled(true);
        this.skip5.setEnabled(true);
        this.starttest.setEnabled(false);
            
            query="insert into Test(canROLLNO,format_Id)"+"values('"+rollno+"','"+fid+"')";
            cb.insertData(query);
            if(k<arrsize)
            {
                query="select QuestionDesc,1stOption,2ndOption,3rdOption,4thOption,crtOption from Question where cat_id='"+n[k]+"'";
                rset=cb.getData(query);
                while(rset.next())
                {
                    strar1[m]=rset.getString("QuestionDesc");
                    strar2[m]=rset.getString("1stOption");
                    strar3[m]=rset.getString("2ndOption");
                    strar4[m]=rset.getString("3rdOption");
                    strar5[m]=rset.getString("4thOption");
                    strar6[m]=rset.getString("crtOption");
                    System.out.println("dis:"+strar6[m]);
                    m++;
                }
                m=0;
                while(m<5)
                {
                    if(m==0)
                    {
                        this.questarea1.setText(strar1[m]);
                        this.opt_1.setText(strar2[m]);
                        this.opt_2.setText(strar3[m]);
                        this.opt_3.setText(strar4[m]);
                        this.opt_4.setText(strar5[m]);
                    }
                    else if(m==1)
                    {
                         this.questarea2.setText(strar1[m]);
                         this.opt2_1.setText(strar2[m]);
                         this.opt2_2.setText(strar3[m]);
                         this.opt2_3.setText(strar4[m]);
                         this.opt2_4.setText(strar5[m]);
                    }
                    else if(m==2)
                    {
                         this.questarea3.setText(strar1[m]);
                         this.opt3_1.setText(strar2[m]);
                         this.opt3_2.setText(strar3[m]);
                         this.opt3_3.setText(strar4[m]);
                         this.opt3_4.setText(strar5[m]);
                    }
                    else if(m==3)
                    {
                         this.questarea4.setText(strar1[m]);
                         this.opt4_1.setText(strar2[m]);
                         this.opt4_2.setText(strar3[m]);
                         this.opt4_3.setText(strar4[m]);
                         this.opt4_4.setText(strar5[m]);
                    }
                    else if(m==4)
                    {
                         this.questarea5.setText(strar1[m]);
                         this.opt5_1.setText(strar2[m]);
                         this.opt5_2.setText(strar3[m]);
                         this.opt5_3.setText(strar4[m]);
                         this.opt5_4.setText(strar5[m]);
                    }
                    m++;
                    counter++;
                }
            }
            query="select TestTime from TestFormat where FormatId='"+fid+"'";
            rset=cb.getData(query);
            while(rset.next())
            {
                time=rset.getInt("TestTime");
            }
        }
         catch(Exception e)
         {
           JOptionPane.showMessageDialog(null, e.getMessage());
         }
         new Thread(new Runnable() 
        {

            @Override
            public void run() 
            {
                int timer=time*60;
                int tam;
                while(true)
                {
                    if( timer % 60 == 0)
                    {
                        tam = 60;
                        time--;
                    }
                    else
                       tam = timer % 60;
                   if(tam == 60)
                       timerlbl.setText((time+1)+":"+"00");
                     else
                    {
                       if(tam>= 10)   
                           timerlbl.setText(time+" : "+tam);
                       else
                           timerlbl.setText(time+" : 0"+tam);
                    }
                   try 
                   {
                       Thread.sleep(1000);
                       timer--;
                       if(timer == 0 )
                       {
                          timerlbl.setText("00 : 00");
                          JOptionPane.showMessageDialog(null, "Time's up dude!");
                          break;
                       }
                       else if(is_completed== true)
                       {
                           JOptionPane.showMessageDialog(null,"Test Has Finished ");
                           Dispose();
                           break;
                       }
                   }
                   catch (Exception ex)
                   {
                       JOptionPane.showMessageDialog(null,ex.getMessage());
                   }
                }
            }
        }).start();
      
    }//GEN-LAST:event_starttestActionPerformed

    public void Dispose()
    {
        this.dispose();
    }
    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed

        
        if(counter<10&&m<10)
        {
            while(arr<5)
            {
                if(arr==0)
                {
                    this.questarea1.setText(strar1[m]);
                    this.opt_1.setText(strar2[m]);
                    this.opt_2.setText(strar3[m]);
                    this.opt_3.setText(strar4[m]);
                    this.opt_4.setText(strar5[m]);
                }
                else if(arr==1)
                {
                    this.questarea2.setText(strar1[m]);
                    this.opt2_1.setText(strar2[m]);
                    this.opt2_2.setText(strar3[m]);
                    this.opt2_3.setText(strar4[m]);
                    this.opt2_4.setText(strar5[m]);

                }
                else if(arr==2)
                {
                    this.questarea3.setText(strar1[m]);
                    this.opt3_1.setText(strar2[m]);
                    this.opt3_2.setText(strar3[m]);
                    this.opt3_3.setText(strar4[m]);
                    this.opt3_4.setText(strar5[m]);

                }
                else if(arr==3)
                {
                    this.questarea4.setText(strar1[m]);
                    this.opt4_1.setText(strar2[m]);
                    this.opt4_2.setText(strar3[m]);
                    this.opt4_3.setText(strar4[m]);
                    this.opt4_4.setText(strar5[m]);

                }
                else if(arr==4)
                {
                    this.questarea5.setText(strar1[m]);
                    this.opt5_1.setText(strar2[m]);
                    this.opt5_2.setText(strar3[m]);
                    this.opt5_3.setText(strar4[m]);
                    this.opt5_4.setText(strar5[m]);
                }
                arr++;
                counter++;
                m++;
            }
            k++;
            
        }
        else
        {
            counter=0;
            if(k<arrsize)
            {
                m=0;
                try 
                {
                    query="select QuestionDesc,1stOption,2ndOption,3rdOption,4thOption,crtOption from Question where cat_id='"+n[k]+"'"; 
                    rset=cb.getData(query);
                    while(rset.next())
                    {
                        strar1[m]=rset.getString("QuestionDesc");
                        strar2[m]=rset.getString("1stOption");
                        strar3[m]=rset.getString("2ndOption");
                        strar4[m]=rset.getString("3rdOption");
                        strar5[m]=rset.getString("4thOption");
                        strar6[m]=rset.getString("crtOption");
                        System.out.println("dis:"+strar6[m]);
                        m++;
                    }
                    m=0;
                    while(m<5)
                    {
                        if(m==0)
                        {
                            this.questarea1.setText(strar1[m]);
                            this.opt_1.setText(strar2[m]);
                            this.opt_2.setText(strar3[m]);
                            this.opt_3.setText(strar4[m]);
                            this.opt_4.setText(strar5[m]);
                        }
                        else if(m==1)
                        {
                            this.questarea2.setText(strar1[m]);
                            this.opt2_1.setText(strar2[m]);
                            this.opt2_2.setText(strar3[m]);
                            this.opt2_3.setText(strar4[m]);
                            this.opt2_4.setText(strar5[m]);
                        }
                        else if(m==2)
                        {
                            this.questarea3.setText(strar1[m]);
                            this.opt3_1.setText(strar2[m]);
                            this.opt3_2.setText(strar3[m]);
                            this.opt3_3.setText(strar4[m]);
                            this.opt3_4.setText(strar5[m]);
                        }
                        else if(m==3)
                        {
                            this.questarea4.setText(strar1[m]);
                            this.opt4_1.setText(strar2[m]);
                            this.opt4_2.setText(strar3[m]);
                            this.opt4_3.setText(strar4[m]);
                            this.opt4_4.setText(strar5[m]);
                        }
                        else if(m==4)
                        {
                            this.questarea5.setText(strar1[m]);
                            this.opt5_1.setText(strar2[m]);
                            this.opt5_2.setText(strar3[m]);
                            this.opt5_3.setText(strar4[m]);
                            this.opt5_4.setText(strar5[m]);
                        }
                     m++;
                     counter++;
                    }
                    arr=0;
                }
                catch(Exception e)
                {
                    JOptionPane.showMessageDialog(null, e.getMessage());
                }
            }
            else
            {
                JOptionPane.showMessageDialog(null, "All submitted");
            }
        }
    }//GEN-LAST:event_nextActionPerformed

    private void opt3_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt3_4ActionPerformed
        canans=this.opt3_4.getText();
    }//GEN-LAST:event_opt3_4ActionPerformed

    private void opt_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt_4ActionPerformed
        canans=this.opt_4.getText();
    }//GEN-LAST:event_opt_4ActionPerformed

    private void opt2_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt2_4ActionPerformed
        canans=this.opt2_4.getText();
    }//GEN-LAST:event_opt2_4ActionPerformed

    private void submit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit1ActionPerformed

        if(canans!=null)
        {
            this.opt_1.setSelected(false);
            this.opt_2.setSelected(false);
            this.opt_3.setSelected(false);
            this.opt_4.setSelected(false);
            try
            {
               query="insert into CompletedTest(canROLLNo,canAns,crtAns)"+"values('"+rollno+"','"+canans+"','"+strar6[j]+"')";
               cb.insertData(query);
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
            this.questarea1.setText("");
            this.opt_1.setText("");
            this.opt_2.setText("");
            this.opt_3.setText("");
            this.opt_4.setText("");
     System.out.println("ans:"+j);
        }
        else
        {
            JOptionPane.showMessageDialog(null, "First select the option");
        }
    }//GEN-LAST:event_submit1ActionPerformed

    private void opt_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt_1ActionPerformed

        canans=this.opt_1.getText();
        
    }//GEN-LAST:event_opt_1ActionPerformed

    private void opt_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt_2ActionPerformed
        canans=this.opt_2.getText();
    }//GEN-LAST:event_opt_2ActionPerformed

    private void opt_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt_3ActionPerformed
       canans=this.opt_3.getText();
    }//GEN-LAST:event_opt_3ActionPerformed

    private void opt2_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt2_1ActionPerformed
        canans=this.opt2_1.getText();
    }//GEN-LAST:event_opt2_1ActionPerformed

    private void opt2_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt2_2ActionPerformed
        canans=this.opt2_2.getText();
    }//GEN-LAST:event_opt2_2ActionPerformed

    private void opt2_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt2_3ActionPerformed
        canans=this.opt2_3.getText();
    }//GEN-LAST:event_opt2_3ActionPerformed

    private void opt3_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt3_1ActionPerformed
        canans=this.opt3_1.getText();
    }//GEN-LAST:event_opt3_1ActionPerformed

    private void opt3_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt3_2ActionPerformed
        canans=this.opt3_2.getText();
    }//GEN-LAST:event_opt3_2ActionPerformed

    private void opt3_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt3_3ActionPerformed
        canans=this.opt3_3.getText();
    }//GEN-LAST:event_opt3_3ActionPerformed

    private void opt4_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt4_1ActionPerformed
        canans=this.opt4_1.getText();
    }//GEN-LAST:event_opt4_1ActionPerformed

    private void opt4_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt4_4ActionPerformed
        canans=this.opt4_4.getText();
    }//GEN-LAST:event_opt4_4ActionPerformed

    private void opt5_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt5_1ActionPerformed
       canans=this.opt5_1.getText();
    }//GEN-LAST:event_opt5_1ActionPerformed

    private void opt5_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt5_2ActionPerformed
        canans=this.opt5_2.getText();
    }//GEN-LAST:event_opt5_2ActionPerformed

    private void opt5_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt5_3ActionPerformed
        canans=this.opt5_3.getText();
    }//GEN-LAST:event_opt5_3ActionPerformed

    private void opt5_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt5_4ActionPerformed
        canans=this.opt5_4.getText();
    }//GEN-LAST:event_opt5_4ActionPerformed

    private void submit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit2ActionPerformed

        if(canans!=null)
        {
            this.opt2_1.setSelected(false);
            this.opt2_2.setSelected(false);
            this.opt2_3.setSelected(false);
            this.opt2_4.setSelected(false);
            j++;
            try
            {
              query="insert into CompletedTest(canROLLNo,canAns,crtAns)"+"values('"+rollno+"','"+canans+"','"+strar6[j]+"')";
              cb.insertData(query);
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
            this.questarea2.setText("");
            this.opt2_1.setText("");
            this.opt2_2.setText("");
            this.opt2_3.setText("");
            this.opt2_4.setText("");
            System.out.println("ans:"+j);
        }
    }//GEN-LAST:event_submit2ActionPerformed

    private void submit3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit3ActionPerformed

        if(canans!=null)
        {
            j++;
            this.opt3_1.setSelected(false);
            this.opt3_2.setSelected(false);
            this.opt3_3.setSelected(false);
            this.opt3_4.setSelected(false);
            try
            {
                query="insert into CompletedTest(canROLLNo,canAns,crtAns)"+"values('"+rollno+"','"+canans+"','"+strar6[j]+"')";
                cb.insertData(query);
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
            this.questarea3.setText("");
            this.opt3_1.setText("");
            this.opt3_2.setText("");
            this.opt3_3.setText("");
            this.opt3_4.setText("");
            System.out.println("ans:"+j);
        }
        else
        {
            JOptionPane.showMessageDialog(null, "First select the Option");
        }
    }//GEN-LAST:event_submit3ActionPerformed

    private void submit4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit4ActionPerformed

        if(canans!=null)
        {
            j++;
            this.opt4_1.setSelected(false);
            this.opt4_2.setSelected(false);
            this.opt4_3.setSelected(false);
            this.opt4_4.setSelected(false);
            try
            {
                query="insert into CompletedTest(canROLLNo,canAns,crtAns)"+"values('"+rollno+"','"+canans+"','"+strar6[j]+"')";
                cb.insertData(query);
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
           System.out.println("ans:"+j);
            this.questarea4.setText("");
            this.opt4_1.setText("");
            this.opt4_2.setText("");
            this.opt4_3.setText("");
            this.opt4_4.setText("");
        }
        else
        {
            JOptionPane.showMessageDialog(null, "First select the Option");
        }
    }//GEN-LAST:event_submit4ActionPerformed

    private void submit5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit5ActionPerformed

        if(canans!=null)
        {
            j++;
            this.opt5_1.setSelected(false);
            this.opt5_2.setSelected(false);
            this.opt5_3.setSelected(false);
            this.opt5_4.setSelected(false);
            try
            {
                
                query="insert into CompletedTest(canROLLNo,canAns,crtAns)"+"values('"+rollno+"','"+canans+"','"+strar6[j]+"')";
                cb.insertData(query);
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
            if(j>=9)
                j=0;
            else
                j++;
           System.out.println("ans:"+j);
            this.questarea5.setText("");
            this.opt5_1.setText("");
            this.opt5_2.setText("");
            this.opt5_3.setText("");
            this.opt5_4.setText("");
        }
        else
        {
            JOptionPane.showMessageDialog(null, "First select the Option");
        }
    }//GEN-LAST:event_submit5ActionPerformed

    private void skip1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_skip1ActionPerformed
        if(canans!=null)
        {
            str1=this.questarea1.getText();
            str2=this.opt_1.getText();
            str3=this.opt_2.getText();
            str4=this.opt_3.getText();
            str5=this.opt_4.getText();
            this.questarea1.setText("");
            this.opt_1.setText("");
            this.opt_2.setText("");
            this.opt_3.setText("");
        this.opt_4.setText("");

        try 
        {
            query="select QuestionId from Question where QuestionDesc='"+str1+"'";
            rset=cb.getData(query);
            while(rset.next())
            {
               questid=rset.getInt("QuestionId");
            }
            query="select TestId from Test where canRollNo='"+rollno+"'";
            rset=cb.getData(query);
            while(rset.next())
            {
                testid=rset.getInt("TestId");
            }
            query="insert into SkipedQuestion(QuestionId,QuestionDesc,1stOption,2ndOption,3rdOption,4thOption,TestId)"+"values('"+questid+"','"+str1+"','"+str2+"','"+str3+"','"+str4+"','"+str5+"','"+testid+"')";
            cb.insertData(query);
            System.out.println("Successfully saved");
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        j++;
        }
        else
        {
            JOptionPane.showMessageDialog(null, "You have selected the option to submit press Submit button");
        }
    }//GEN-LAST:event_skip1ActionPerformed

    private void skip2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_skip2ActionPerformed

        if(canans!=null)
        {
        str1=this.questarea2.getText();
        str2=this.opt2_1.getText();
        str3=this.opt2_2.getText();
        str4=this.opt2_3.getText();
        str5=this.opt2_4.getText();
        this.questarea2.setText("");
        this.opt2_1.setText("");
        this.opt2_2.setText("");
        this.opt2_3.setText("");
        this.opt2_4.setText("");

        try 
        {
            query="select QuestionId from Question where QuestionDesc='"+str1+"'";
            rset=cb.getData(query);
            while(rset.next())
            {
               questid=rset.getInt("QuestionId");
            }
            query="select TestId from Test where canRollNo='"+rollno+"'";
            rset=cb.getData(query);
            while(rset.next())
            {
                testid=rset.getInt("TestId");
            }
            query="insert into SkipedQuestion(QuestionId,QuestionDesc,1stOption,2ndOption,3rdOption,4thOption,TestId)"+"values('"+questid+"','"+str1+"','"+str2+"','"+str3+"','"+str4+"','"+str5+"','"+testid+"')";
            cb.insertData(query);
            System.out.println("Successfully saved");
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        j++;
        }
        else
        {
          JOptionPane.showMessageDialog(null, "You have selected the option to submit press Submit button");
        }
        
    }//GEN-LAST:event_skip2ActionPerformed

    private void skip3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_skip3ActionPerformed

        if(canans!=null)
        {
        str1=this.questarea3.getText();
        str2=this.opt3_1.getText();
        str3=this.opt3_2.getText();
        str4=this.opt3_3.getText();
        str5=this.opt3_4.getText();
        this.questarea3.setText("");
        this.opt3_1.setText("");
        this.opt3_2.setText("");
        this.opt3_3.setText("");
        this.opt3_4.setText("");

        try 
        {
            query="select QuestionId from Question where QuestionDesc='"+str1+"'";
            rset=cb.getData(query);
            while(rset.next())
            {
               questid=rset.getInt("QuestionId");
            }
            query="select TestId from Test where canRollNo='"+rollno+"'";
            rset=cb.getData(query);
            while(rset.next())
            {
                testid=rset.getInt("TestId");
            }
            query="insert into SkipedQuestion(QuestionId,QuestionDesc,1stOption,2ndOption,3rdOption,4thOption,TestId)"+"values('"+questid+"','"+str1+"','"+str2+"','"+str3+"','"+str4+"','"+str5+"','"+testid+"')";
            cb.insertData(query);
            System.out.println("Successfully saved");
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        j++;
        }
        else
        {
          JOptionPane.showMessageDialog(null, "You have selected the option to submit press Submit button");
        }
    }//GEN-LAST:event_skip3ActionPerformed

    private void skip4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_skip4ActionPerformed

        if(canans!=null)
        {
        str1=this.questarea4.getText();
        str2=this.opt4_1.getText();
        str3=this.opt4_2.getText();
        str4=this.opt4_3.getText();
        str5=this.opt4_4.getText();
        this.questarea4.setText("");
        this.opt4_1.setText("");
        this.opt4_2.setText("");
        this.opt4_3.setText("");
        this.opt4_4.setText("");

        try 
        {
            query="select QuestionId from Question where QuestionDesc='"+str1+"'";
            rset=cb.getData(query);
            while(rset.next())
            {
               questid=rset.getInt("QuestionId");
            }
           query="select TestId from Test where canRollNo='"+rollno+"'";
           rset=cb.getData(query);
            while(rset.next())
            {
                testid=rset.getInt("TestId");
            }
            query="insert into SkipedQuestion(QuestionId,QuestionDesc,1stOption,2ndOption,3rdOption,4thOption,TestId)"+"values('"+questid+"','"+str1+"','"+str2+"','"+str3+"','"+str4+"','"+str5+"','"+testid+"')";
            rset=cb.getData(query);
            System.out.println("Successfully saved");
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        j++;
        }
        else
        {
           JOptionPane.showMessageDialog(null, "You have selected the option to submit press Submit button");
        }
    }//GEN-LAST:event_skip4ActionPerformed

    private void skip5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_skip5ActionPerformed

        if(canans!=null)
        {
        str1=this.questarea5.getText();
        str2=this.opt5_1.getText();
        str3=this.opt5_2.getText();
        str4=this.opt5_3.getText();
        str5=this.opt5_4.getText();
        this.questarea5.setText("");
        this.opt5_1.setText("");
        this.opt5_2.setText("");
        this.opt5_3.setText("");
        this.opt5_4.setText("");
        try 
        {
            query="select QuestionId from Question where QuestionDesc='"+str1+"'";
            rset=cb.getData(query);
            while(rset.next())
            {
               questid=rset.getInt("QuestionId");
            }
            query="select TestId from Test where canRollNo='"+rollno+"'";
            rset=cb.getData(query);
            while(rset.next())
            {
                testid=rset.getInt("TestId");
            }
            query="insert into SkipedQuestion(QuestionId,QuestionDesc,1stOption,2ndOption,3rdOption,4thOption,TestId)"+"values('"+questid+"','"+str1+"','"+str2+"','"+str3+"','"+str4+"','"+str5+"','"+testid+"')";
            cb.insertData(query);
            System.out.println("Successfully saved");
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        j++;
        }
        else
        {
          JOptionPane.showMessageDialog(null, "You have selected the option to submit press Submit button");
        }
           
    }//GEN-LAST:event_skip5ActionPerformed

    /**
     * @param args the command line arguments
     */
    
public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewFiveQuestions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewFiveQuestions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewFiveQuestions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewFiveQuestions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewFiveQuestions().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextArea jTextArea5;
    private javax.swing.JButton next;
    private javax.swing.JRadioButton opt2_1;
    private javax.swing.JRadioButton opt2_2;
    private javax.swing.JRadioButton opt2_3;
    private javax.swing.JRadioButton opt2_4;
    private javax.swing.JRadioButton opt3_1;
    private javax.swing.JRadioButton opt3_2;
    private javax.swing.JRadioButton opt3_3;
    private javax.swing.JRadioButton opt3_4;
    private javax.swing.JRadioButton opt4_1;
    private javax.swing.JRadioButton opt4_2;
    private javax.swing.JRadioButton opt4_3;
    private javax.swing.JRadioButton opt4_4;
    private javax.swing.JRadioButton opt5_1;
    private javax.swing.JRadioButton opt5_2;
    private javax.swing.JRadioButton opt5_3;
    private javax.swing.JRadioButton opt5_4;
    private javax.swing.JRadioButton opt_1;
    private javax.swing.JRadioButton opt_2;
    private javax.swing.JRadioButton opt_3;
    private javax.swing.JRadioButton opt_4;
    private javax.swing.JTextArea questarea1;
    private javax.swing.JTextArea questarea2;
    private javax.swing.JTextArea questarea3;
    private javax.swing.JTextArea questarea4;
    private javax.swing.JTextArea questarea5;
    private javax.swing.JButton skip1;
    private javax.swing.JButton skip2;
    private javax.swing.JButton skip3;
    private javax.swing.JButton skip4;
    private javax.swing.JButton skip5;
    private javax.swing.JButton starttest;
    private javax.swing.JButton submit1;
    private javax.swing.JButton submit2;
    private javax.swing.JButton submit3;
    private javax.swing.JButton submit4;
    private javax.swing.JButton submit5;
    private javax.swing.JLabel timerlbl;
    // End of variables declaration//GEN-END:variables
}
